### ISSUE TITLE
Hangouts Load More button takes you to the top of the page after clicking it

### ISSUE THREAD

**Issue by AnnaDodson** [codebuddies/codebuddies#1003]
Bug. Related to the PR #1002 for issue #938 

What is the current behavior?
Currently, when clicking on the load more button, more Hangouts are loaded but the page scrolls to the top and you need to scroll all the way back down again to find your place.

What is the expected behavior?
I would expect to click the button and the Hangouts be dynamically loaded in so my place isn't lost on the screen.

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)
Affected on Firefox and Chrome on Ubuntu and Android Firefox on mobile 

I'm happy to raise a PR for this if required.

**Comment by AnnaDodson** [comment]
Great! Will do. I'll wait for the review on PR #1002 before raising a PR for this one in case there are any issues. Thanks :smile:

**Comment by lpatmo** [comment]
@AnnaDodson Btw, thanks for coming back and contributing to CB for two consecutive Hacktoberfest years! (Saw that you've posted here before in 2016. :))

**Comment by AnnaDodson** [comment]
Thank you! It was nice coming back to it and being able to fix something :smile:
