### ISSUE TITLE
CSS adjustments for hangout card

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1009]
1) When the study group title is too long, it is too close to the "i" icon

2) Expand and center the "RSVP to this Hangout" button; right now it is very narrow.

Let's make the button look more like:

![image](https://user-images.githubusercontent.com/4512699/46783710-288efc00-cce0-11e8-9eb2-75cd0c537aa9.png)

3) Remove the "Join now" green button from "LIVE NOW"/active events

**Comment by mendaomn** [comment]
Hey, I'd like to take up the issue! :) Trying to set everything up right now

**Comment by lpatmo** [comment]
I just realized that all my copy/paste screenshots were off. Will edit the post shortly!

**Comment by jhorner32** [comment]
@mendaomn, let me know if you need any help. I'd love to help on this as well :)

**Comment by mendaomn** [comment]
Hey, I'm working on the issue

How can I reproduce a "live now" hangout? I've gone ahead and set `feeder: true` but it doesn't populate with live events

**Comment by lpatmo** [comment]
@mendaomn You need to click on the "schedule a hangout" button on codebuddies.org/hangouts. The default start time will be "now," so when you schedule one the hangout will be scheduled to start automatically, and will be "live now."

Oh, yes -- the title should be blue, according to the screenshot. Thanks for catching!
