### ISSUE TITLE
Dev instances of Codebuddies should not log messages to #codebuddies-ops

### ISSUE THREAD

**Issue by sebbel** [codebuddies/codebuddies#1019]
kinda spammy but for every hangout in every dev instance out there, we get a message in #codebuddies-ops

**Comment by lpatmo** [comment]
I think you can set which Slack channel your test hangout alerts on line 38 in settings-development.json: 

```  "slack_alert_channel": "#codebuddies-ops",```

We could create a new Slack channel (#codebuddies-test-hangouts) and have all the local hangout notifications log there. (Update: just created it. :))

Hacktoberfest PR proposal:
- Update `#codebuddies-ops` to be `#codebuddies-test-hangouts` in settings-development.json

**Comment by vividh** [comment]
I'll take this!
Suggestion: `isModeProduction` can be relied on to not send slack messages in dev mode. Should I include that as well?

**Comment by lpatmo** [comment]
Thanks @vividh! We're actually still sending the notifications to #codebuddies-ops even when `isModeProduction` is false, heh. I do think it's important to see these messages -- eg when we're testing the formatting of these messages, or testing that they are firing as expected.

So this change should be pretty straightforward: changing #codebuddies-ops to #codebuddies-test-hangouts.

**Comment by vividh** [comment]
Alright. Will send PR in a while!
