### ISSUE TITLE
Slack reminder alerts are not sending out

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1020]
We have a bit of code that sends out reminders to the #announcements channel that a hangout is set to start in less than 2 hours (see: `server/slack/methods.js`): 

```
if (type === "REMINDER") {
    fallback =
      `Reminder! hangout: ${hangout.topic} is set to start on ${
        hangout.start_time
      }. Visit` + Meteor.absoluteUrl("hangout/" + hangout._id);
    pretext = `Reminder! ${hangout.type} hangout: *${
      hangout.topic
    }* scheduled by a CodeBuddies member is set to start in *less than two hours!* ${nameString}`;
  }
```

However, although announcements about new hangouts are firing, this reminder code is not. Wonder if someone could look into it.

**Comment by yoksanherlie** [comment]
I would like to work on this :)
Can you tell me how to reproduce this issue? Do I just create a new hangout?

**Comment by lpatmo** [comment]
@yoksanherlie I noticed that in the #codebuddies-ops test channel, there were some reminder alerts. Were they from you? And did you get them to fire after changing any code, or did they simply seem to work? Also, did you notice any duplicates firing?

![image](https://user-images.githubusercontent.com/4512699/47252617-85836400-d3fc-11e8-8c26-2a6624d7b987.png)

**Comment by yoksanherlie** [comment]
@lpatmo Yes, it's from me because I tried to debug it with my own dummy data. It will notify through the #codebuddies-ops channel by default because of the settings-development.json but it hasn't notify to the #announcements channel, that's the bug I want to fix from your request of this issue

**Comment by yoksanherlie** [comment]
Yes, I was able to recreate the bug.
So, is this fix necessary? That will remind to the slack #announcements channel when there is a upcoming hangout in 2 hours?
If yes, I will make a pr.
