### ISSUE TITLE
Redirect new users to the "welcome" page after they sign up for the first time

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1021]
After a new user signs up for the first time (aka after they see this screen):
![image](https://user-images.githubusercontent.com/4512699/47252236-fa06d480-d3f5-11e8-9507-2729165576ca.png)

... let's redirect them to https://codebuddies.org/welcome. 

We're using `FlowRouter`, so the URL path should be something like `FlowRouter.go("path")`. 

If you're a new contributor and need to get set up, please check out docs.codebuddies.org. And let us know if you have questions!

**Comment by FrikanRw** [comment]
Can I pick this issue up, please?

**Comment by railsstudent** [comment]
@FrikanRw  It is yours.

**Comment by lpatmo** [comment]
@FrikanRw Do you need any help with this issue?

**Comment by FrikanRw** [comment]
@lpatmo I have been trying to log in just to test my changes, can I add the FlowRouter.go("/welcome") on the "updateBasicInformation" call?

**Comment by FrikanRw** [comment]
Took a stab at it [here](https://github.com/codebuddies/codebuddies/pull/1039).

**Comment by lpatmo** [comment]
@FrikanRw Thanks, will take a look! Is login using Github working for you on localhost:3000? If you type `meteor reset` that's how you can clear the database to simulate logging in as a new user again.
