### ISSUE TITLE
CSS issue on 'welcome' page

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1022]
See: 

![image](https://user-images.githubusercontent.com/4512699/47252256-a34dca80-d3f6-11e8-8e0a-f2adf53cdaf0.png)

This currently only appears on https://staging.codebuddies.org/welcome. It's related to some CSS tweaks merged in a previous PR that adjusted the styling of the h1 on the staging.codebuddies.org/study-groups page, I believe.

TODO: fix this on the welcome page and double check that it doesn't break other pages.

**Comment by TomerPacific** [comment]
Hi @lpatmo ,
I would like to tackle this issue. Anything else I should be aware of other than what you said?

**Comment by lpatmo** [comment]
We use SASS, and the CSS compiles automatically when you run localhost:3000. Docs are at docs.codebuddies.org. Let me know if you have any questions. Thanks!

**Comment by TomerPacific** [comment]
@lpatmo , seeing as there is a pull request to close this issue, there is no need for me to work on it. Right?

**Comment by lpatmo** [comment]
@TomerPacific I took a look at @bgalek's PR. It was bad form for them to take on the issue w/out commenting first to check if anyone else had already claimed it, but looks like the fix was that easy. Sorry this happened.
