### ISSUE TITLE
Update the "welcome" text on the codebuddies.org/welcome page and welcome email

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1023]
The two files that need to be updated: 
- private/templates/email/welcome_message.html
- client/templates/other/welcome.html

This is a `good-for-beginners`, pure HTML issue.

Please update the text to say:

------------------------------------------------------------

***What exactly is CodeBuddies?*** 

We’re a community of independent code learners sharing knowledge and helping each other learn faster.

We're 100% volunteer.  

Our website, [codebuddies.org](https://codebuddies.org) is open-sourced and welcomes contributions on [https://github.com/codebuddies/codebuddies](https://github.com/codebuddies/codebuddies).

We come from all over the world.  We're all different ages; we work and study across all sorts of professions.

Everyone is welcome -- no previous experience required!  

This community thrives thanks to the generosity of our members, Slack admin moderators, GitHub code contributors, community mentors, and donations on https://opencollective.com/codebuddies.

***Getting Started***
1) Please check your email. If you don't see an invite to the CodeBuddies Slack, please sign yourself up [here](https://codebuddiesmeet.herokuapp.com).

2) Don't be shy! Introduce yourself in the #introduce-yourself Slack channel, or on our forum at https://forum.codebuddies.org/t/introduce-yourself-here/38/7, and welcome fellow new members. The more we know about each other, the better we can connect and collaborate. :) 

3) You’ll automatically be invited to a couple of default Slack channels. You can browse all our public Slack channels by clicking on the  "Channels" link in the sidebar. Make sure to read our [CodeBuddies Slack Etiquette for General Members](https://codebuddies.org/slack).

4) Log into our website at http://codebuddies.org using your Github or new CodeBuddies Slack account and take a look around -- or join a hangout! Hangouts are a way to study silently or pair program live with other members of the community. There are three types of hangouts you can start: silent, teaching, or collaborative.

When a hangout is scheduled, it'll get automatically posted back to our Slack #announcements channel.

We've also got a [24/7 silent coworking hangout](https://codebuddies.org/coworking) you can join at any time, without scheduling one. 

By default, our custom is to turn off video camera during these hangouts. Voice chat and screensharing (recommended) are optional. 

If you start a hangout we'll give you a way to meet on a CodeBuddies page by default, but you can also advertise an external hangout hosted on Twitch, Zoom, YouTube Livestream etc. if you prefer an alternative platform! 

PS Check out the `@cb_jarvis` command on Slack to schedule a hangout directly from Slack!

5) Interested in going deep on topics like functional javascript or that special ruby book or blockchain? Start a study group on codebuddies.org/study-groups! All study groups created on the website are announced on the #announcements channel in Slack, and as the owner of a group, you can also set up Slack channels to receive an alert when a hangout is scheduled in that group. 

Study groups offer different tools to help connect people with similar learning goals, with the hope that they can motivate each other. 

6) If you have any questions about the community or the project or want to talk to an admin, feel free to ask about it in the #codebuddies-meta Slack channel. That’s also where discussions related to our community happen.

Happy learning!

***Quick Links***
[Website](http://codebuddies.org)
[FAQ](http://codebuddies.org/faq)
[Github](https://github.com/codebuddies)
[Github: Website](https://github.com/codebuddies/codebuddies)
[Open Collective](https://opencollective.com/codebuddies)
[Slack Invite](https://codebuddiesmeet.herokuapp.com)

[Forum](https://forum.codebuddies.org)
[Twitter](http://twitter.com/codebuddiesmeet)
[Facebook Group](https://www.facebook.com/groups/TOPSTUDYGROUP/)
[YouTube](https://www.youtube.com/channel/UCOBp46r9_g8kKRCc0y-rJVg)

------------------------------------------------------------

Please note: the text above is slightly different from the text on https://codebuddies.org/welcome.

**Comment by ekanshiag** [comment]
Hi, I will pick this one up.

**Comment by n0zg** [comment]
Hi, i made a pull request updating both pages :)
