### ISSUE TITLE
Suggestion : Implementing a Discord server

### ISSUE THREAD

**Issue by imsmokie** [codebuddies/codebuddies#1033]
Discord is an application similar to slack

**Comment by lpatmo** [comment]
Thanks for filing this, @imsmokie! I see many people in the community who love Slack, and many people who dislike Slack (but aren't as vocal about it on Slack, for obvious reasons).

The main problem we have with Slack is the lost messages (we have about ~400K messages not viewable in history), so we created forum.codebuddies.org to try to preserve more of those conversations.

That said, I think creating others spaces for users who aren't heavy forum/Slack/hangout/Facebook users makes sense, so here's an invite link to the brand new CodeBuddies Discord server: https://discord.gg/4a9T3zn
