### ISSUE TITLE
Add an anchor link to the "Where should I share a commercial post on Slack?" header on codebuddies.org/slack

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1044]
I occasionally find myself referencing the "Where should I share a commercial post on Slack?" section on codebuddies.org/slack, but right now users have to scroll, since there is no _direct_ link to that section.

Proposal:
Add an anchor tag to the ```<h1>Where should I share a commercial post on Slack?</h1>``` on codebuddies.org/slack page, so that users can type in https://codebuddies.org/slack#commercial and land directly on that section of the page. 

This is a `good-for-beginners` and `good-first-issue` issue. Docs are at https://docs.codebuddies.org.

**Comment by akarshsingh9** [comment]
Can I take this one?

**Comment by akarshsingh9** [comment]
How can I reproduce this issue? I am not able to locate the file

**Comment by lpatmo** [comment]
@akarshsingh9 The file is here: 
```
$ ag "Where should I"
client/templates/other/slack.html
150:                <h1>Where should I share a commercial post on Slack?</h1>
```

**Comment by lpatmo** [comment]
@akarshsingh9 If you have trouble setting up the development environment based on the steps at docs.codebuddies.org, let me know!

**Comment by akarshsingh9** [comment]
Hi, please review PR #1066. Sorry it took some time to set up the working environment on my laptop
