### ISSUE TITLE
increase prettier's default line length to 100.

### ISSUE THREAD

**Issue by distalx** [codebuddies/codebuddies#1045]
default line length is 80, increase that to 100. [here](https://github.com/codebuddies/codebuddies/blob/staging/package.json#L17)
i.e. `"prettier --print-width 80 --write"`
Ref : https://prettier.io/docs/en/options.html#print-width

**Comment by GurpreetSK95** [comment]
Is anyone working on this issue yet? I would like to take this up.

**Comment by GurpreetSK95** [comment]
Is someone working on this issue?

**Comment by distalx** [comment]
@GurpreetSK95  It is yours.
