### ISSUE TITLE
add seeder for `discussions` collection. 

### ISSUE THREAD

**Issue by distalx** [codebuddies/codebuddies#1047]
Current seeders can be found [here](https://github.com/codebuddies/codebuddies/tree/staging/server/seeder), These seeders are being used to populate the dummy data. 

Seeders can be turn on and off by updating this [flag](https://github.com/codebuddies/codebuddies/blob/staging/settings-development.json#L32), inside seetings-development.json file.

here is the schema for discussions collection.
```
{
  "_id": "8XNkQYAhpJDr62grA",
  "author": {
    "id": "FL8H6YM6kAMtB4B8S",
    "username": "distalx",
    "avatar": "http://www.gravatar.com/avatar/581ebcb1cd2e62c3c9e12896529bceae?size=72"
  },
  "created_at": "2018-10-27T17:09:05.542Z",
  "description": "test 123",
  "down_votes": [],
  "modified_at": null,
  "response_count": 0,
  "study_group": {
    "id": "CB",
    "title": "CB",
    "slug": "CB"
  },
  "tags": [
    "general"
  ],
  "topic": "test 1",
  "up_votes": [],
  "views": 0
}
```

**Comment by ahmadnurus** [comment]
Can i work on this?

**Comment by railsstudent** [comment]
@ahmadnurus  Yep.

**Comment by dantesolis** [comment]
may I take this one?

**Comment by railsstudent** [comment]
@dantesolis   Sorry, @ahmadnurus  already claimed it.
