### ISSUE TITLE
Scroll back up after redirect to /welcome page for new user signup

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1049]
To reproduce:
1) `meteor reset`
2) Start up the app (`meteor --settings settings-development.json`)
3) Log in using Github or Slack to "sign up" a new user

```After the redirect, the page does not scroll back to top. jQuery might do the trick.
i.e. $("html, body").animate({ scrollTop: 0 }, "fast");
``` 
-- @distalx 

For context, see: #1039

**Comment by Blasz** [comment]
I'll work on this if that's okay.

**Comment by wuworkshop** [comment]
Go for it @Blasz
