### ISSUE TITLE
Minor changes to the copy on the CB homepage

### ISSUE THREAD

**Issue by wuworkshop** [codebuddies/codebuddies#1051]
Currently on the CodeBuddies homepage it says:

> CodeBuddies is a community of 4000+ code learners who help each other through conversations on Slack and peer-to-peer organized study groups and virtual hangouts.

I would like the homepage copy to set more accurate expectations and just have the "4000+" part removed. It might also be good to add the word "global". So the revised line would say:

> CodeBuddies is a global community of code learners who help each other through conversations on Slack and peer-to-peer organized study groups and virtual hangouts.

The second sentence to change is the following:

>This project is free and transparent on Open Collective, non-profit, open-sourced, and powered by a fantastic team of core volunteer contributors.

CodeBuddies is really more a not-for-profit than a non-profit. See the differences listed here:
https://strategiccfo.com/non-profit-vs-profit/

The second sentence should be revised to say:

>This project is free and transparent on Open Collective, not-for-profit, open-sourced, and powered by a fantastic team of core volunteer contributors.

**Comment by wrejcodes** [comment]
I can take this one if you would like :)
