### ISSUE TITLE
Update codebuddies.org/welcome with screenshots

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1059]
The new welcome guide that new users get redirected to after they sign up is great, but looks a bit text-heavy:

![image](https://user-images.githubusercontent.com/4512699/47613070-1f728e80-da45-11e8-9e32-ae4e57b3a3a3.png)

Proposal: add screenshots to this page.

Place to add screenshots: 
`/public/images`

File to edit:
`/client/templates/other/welcome.html`

**Comment by Bobeta** [comment]
I'll help you with this 😅

**Comment by railsstudent** [comment]
Claimed by @Bobeta
