### ISSUE TITLE
Add the #mud channel to the list of Slack notification channels

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1064]
We need to add `mud` to the list of channels in these two files: `imports/data/slack_channels.js` and `imports/data/discussion_tags.js`

**Comment by RoyJia** [comment]
Pick

**Comment by RoyJia** [comment]
@lpatmo Please help to review - https://github.com/codebuddies/codebuddies/pull/1065

**Comment by lpatmo** [comment]
Thanks @RoyJia!
