### ISSUE TITLE
Learnings stripping out '@' character from Twitter post

### ISSUE THREAD

**Issue by brylie** [codebuddies/codebuddies#1075]
What is the current behavior?

When adding learnings with the '@' character, it seems to be stripped from the output on Twitter.

What is the expected behavior?

Learnings would publish to Twitter with the '@' symbol, so I can @mention participants.

**Comment by lpatmo** [comment]
Thanks for filing this! We made a conscious decision to limit this behavior for security reasons. Will explain more in DM.
