### ISSUE TITLE
[UI Bug] Two Patreon icons appear on profile page

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1101]
Noticed that two Patreon icon appeared when I submitted a Patreon link:

![image](https://user-images.githubusercontent.com/4512699/51012490-3851f280-1512-11e9-9b29-2857e29e47d8.png)

Probably an easy bug to fix.

**Comment by noragne** [comment]
I am working on

**Comment by lpatmo** [comment]
Thank you @noragne and @sebbel!
