### ISSUE TITLE
IDEA: Feed scheduled hangouts automatically into a google calendar

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1110]
Proposed by @gauravchl:

```Feature Proposal: Create a Codebuddies google calendar and whenever a new hangout is scheduled add that hangout entry to calendar as well. Others can subscribe to the calendar and can see upcoming or ongoing hangouts right into their own choice of app(apple/yahoo/google whatever calendar they use).```

**Comment by lpatmo** [comment]
Maybe we should embed the Google Calendar to the sidebar on codebuddies.org/hangouts, if this happens.

**Comment by gauravchl** [comment]
Totally 💯

**Comment by railsstudent** [comment]
Does google calendar required to be under codebuddies gmail account and grant public for codebuddies members to see?

**Comment by lpatmo** [comment]
So in the early days (2014) before CB had a proper events website I actually did use Google Calendar to keep track of hangouts in the Google Groups; here is the public calendar:

https://calendar.google.com/calendar/embed?src=codebuddiesdotorg%40gmail.com&ctz=America%2FLos_Angeles

And embed code: <iframe src="https://calendar.google.com/calendar/embed?src=codebuddiesdotorg%40gmail.com&ctz=America%2FLos_Angeles" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

Public address in iCal format:
https://calendar.google.com/calendar/ical/codebuddiesdotorg%40gmail.com/public/basic.ics

**Comment by lpatmo** [comment]
Mockup in browser:

![image](https://user-images.githubusercontent.com/4512699/52778319-9767c300-2ffa-11e9-96ff-acc644aee0a0.png)

**Comment by gauravchl** [comment]
Google calendar will be under Codebuddies Google account. Codebuddies app(Meteor) will use API tokens to add events to it whenever a new hangout is scheduled(+ other CRUD operation). 
https://developers.google.com/calendar/quickstart/nodejs

For other peoples(codebuddies user +non user) this calendar will be read only. and they can subscribe to it using ical feed. Like this one(Liverpoo FC matches): https://calendar.google.com/calendar/ical/p520al5mfgqq5m2a8pu021nv0c%40group.calendar.google.com/public/basic.ics

**Comment by railsstudent** [comment]
> Google calendar will be under Codebuddies Google account. Codebuddies app(Meteor) will use API tokens to add events to it whenever a new hangout is scheduled(+ other CRUD operation).
> https://developers.google.com/calendar/quickstart/nodejs
> 
> For other peoples(codebuddies user +non user) this calendar will be read only. and they can subscribe to it using ical feed. Like this one(Liverpool FC matches): https://calendar.google.com/calendar/ical/p520al5mfgqq5m2a8pu021nv0c%40group.calendar.google.com/public/basic.ics



> Mockup in browser:
> 
> ![image](https://user-images.githubusercontent.com/4512699/52778319-9767c300-2ffa-11e9-96ff-acc644aee0a0.png)

Will there be design in mobile view? The current design will have narrow calendar day cell on mobile phone.  Or should we look for responsive calendar control that looks good on desktop browser and mobile browser? 

cc @lpatmo

**Comment by billglover** [comment]
Is there a reason we’d publish a Google Calendar over an iCal feed?

**Comment by gauravchl** [comment]
@railsstudent May be 🤷‍♂️, it's an iframe  essentially.

**Comment by gauravchl** [comment]
@billglover That's a good point! I haven't thought about this before. In fact we don't need a calendar API setup at all. Just one iCal feed url will do the magic.
Flow would be:
- Create a iCalFeed url(https://codebuddies.org/icalfeed) on website, Publish all upcoming and current hangouts from the past month.
- Users can just use that iCalFeed url to see events inside their own calendars.
- Additionally create a new google calendar with that iCalFeed and iFrame it to website.

**Comment by billglover** [comment]
I think this simplifies things but also removes a dependency on Google.

**Comment by gauravchl** [comment]
Here we go:
https://youtu.be/bD10mGCIo7g
https://github.com/codebuddies/codebuddies/pull/1111

**Comment by lpatmo** [comment]
Thank you so much! I will take a look as soon as I can tonight!

**Comment by lpatmo** [comment]
Ah, it's disappointing that Google Calendar's refresh frequency is "up to every 12 hours" (http://help.cheqroom.com/frequently-asked-questions/how-often-does-google-update-its-calendar-feeds), but still very exciting that we can link up the `i-cal-feed` into a google calendar!

**Comment by lpatmo** [comment]
UPDATE: @gauravchl's work has been merged! Check out https://codebuddies.org/i-cal-feed. :) 

> Will there be design in mobile view? The current design will have narrow calendar day cell on mobile phone. Or should we look for responsive calendar control that looks good on desktop browser and mobile browser?

Sorry @railsstudent, forgot I didn't respond to your question. Decided not to do the embed in part because you're right that the narrow calendar view isn't ideal, and also because the feed not updating automatically will be confusing. 

Re: a calendar view in general -- https://fullcalendar.io/ could be an option, h/t @distalx :) I'll file a new issue about it! It would be very cool (I can see the calendar view UI being on /hangouts or even on a /calendar), but it's not priority. 

Thanks everyone for your input!
