### ISSUE TITLE
Issue: Column headings for 'Topic' and 'Author' out of place on Discussions page

### ISSUE THREAD

**Issue by Dan-Y-Ko** [codebuddies/codebuddies#1120]
On the discussion page, in mobile view, the topic and author text is kind of just lingering there and doesn't look quite right.

![image](https://i.imgur.com/tSbOqOW.png)

**Comment by billglover** [comment]
Page: https://codebuddies.org/discussions

In contrast to the mobile view the two columns show correctly. As author is not a term that can be sorted or filtered, I'm not sure it makes sense to have this broken out as a separate column. One idea could be to remove the column headings and include the author name as part of the hangout description. The mobile view appears to do this already.

**Comment by cbelsole** [comment]
Sorry @Dan-Y-Ko. I did not see you were assigned to this until after I put out the review.
