### ISSUE TITLE
Feature: support text formatting options for posts on the Discussion page

### ISSUE THREAD

**Issue by RuubixO** [codebuddies/codebuddies#1122]
Do you want to request a feature or report a bug?
Feature

What is the current behavior?
This would be an expansion of the options for setting up a proposal in "Discussions".
![screenshot from 2019-02-25 21-19-03](https://user-images.githubusercontent.com/20217139/53382961-f820c500-3943-11e9-8a10-0f6ef9daef94.png)

What is the expected behavior?
When I got to 'write' the new Discussion, I would like a tray of options (in the form of icons/text) below the dialog box, as seen in this 1st screenshot:
(disclaimer: I'm using this as an example, directly from my google gmail, I do not own any of the material shown).
![screenshot from 2019-02-25 21-23-06](https://user-images.githubusercontent.com/20217139/53382960-1b4b7480-3944-11e9-802f-755e1228d0b6.png)

In particular, to create custom html links to reduce the verbosity of posts. 

- It might be good to offer ways to link images and other materials. Attaching docs would be convenient.

- Since we have good google integration, maybe a way to directly share some content from Drive. This would be awesome for shared study materials--could be possible for other people to add materials in the proceeding discussion-thread?

- A way to transfer the discussion attachments and formatting into the subsequent CB-Hangouts I would schedule.

Thanks again!

If there was a keyboard combination that could reach the same effect, this would also work (for me*), as long as there was some way to offer a pop-up or dialogue box that could elaborate.

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)

**Comment by billglover** [comment]
If implemented I would have a strong preference for the use of Markdown.

**Comment by billglover** [comment]
I think there is a solid use-case for supporting links. I'm less convinced on the need to attach documents, support the embedding of pictures, or the use of custom font styling. Shared study materials could be linked rather than duplicated as attachments.

Is there a use-case that is not served by the addition of support for links?

**Comment by RuubixO** [comment]
@billglover I thought about it, and agree that links are sufficient for me. It would be nice to have google drive integration so that links would go directly to a specific shared document or folder, though.

**Comment by RuubixO** [comment]
Separately, I've been frustrated that I can't format my text in the discussion page. The lack of paragraph or bullet-point formatting can make more than a few lines of texts messy and disorganized.

**Comment by distalx** [comment]
@RuubixO,  Styling with Markdown is already supported :)

I think we need to mention that somewhere on the discussion creation modal to improve the user experience.
i.e.  `Styling with Markdown is supported`.

**Comment by billglover** [comment]
@RuubixO It looks as though this feature was already supported but wasn't obvious that it existed. I have subsequently used markdown to format text in discussion posts and to include links to documents hosted on Google Drive. This sounds like it gives you the tools you need.

Markdown support is live at the moment. Whilst the help text is worked on to give the feature greater visibility, can you confirm that this gives you what you need?
