### ISSUE TITLE
Add legal text to Hangout Tips section

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1135]
Insert the following text into the `Hangout Tips` list:

2/ You agree not to stream copyrighted or otherwise objectionable content in the hangout. 

![image](https://user-images.githubusercontent.com/4512699/55111845-80f06500-5098-11e9-988f-d78b334a59ca.png)

**Comment by peoray** [comment]
Can you provide more details on this. Would love to work on it

**Comment by peoray** [comment]
Which of the template is this?

**Comment by lpatmo** [comment]
Do you have https://github.com/ggreer/the_silver_searcher installed? If so,
try typing `ag "Hangout Tips"`, and you should be able to see where the
template is. Or try using `grep` to search for where the file is located.
Let me know if you get stuck.

**Comment by peoray** [comment]
Is this on my editor?

**Comment by lpatmo** [comment]
On your terminal. :)

**Comment by peoray** [comment]
Okay, figured it out. Although, I'm having issues with the installation. Seems like I need to install some package. I already did `meteor npm install`

**Comment by lpatmo** [comment]
Can you share a screenshot?

**Comment by peoray** [comment]
Working now, although it posted it in the slack group.

From my ag search, there are three files that have Hangout tips, I'll include the addition in all three?

**Comment by lpatmo** [comment]
Sure!
