### ISSUE TITLE
Issue: open security vulnerabilities

### ISSUE THREAD

**Issue by billglover** [codebuddies/codebuddies#1139]
[issue redacted]

**Comment by billglover** [comment]
Open Vulnerabilities at the time of posting:

* 💥 js-yaml
* 💥 lodash
* 💥 tar
* 🔥 braces
* 🔥 stringstream
* 🔥 fstream
* 🔥 jquery
* 🔥 mem
* 🔥 underscore.string

Do we want to break these out as separate issues to make them more manageable/easy to pick off?

**Comment by sebbel** [comment]
@billglover ?

**Comment by lpatmo** [comment]
@sebbel We're fixing this privately so it's more secure!
