### ISSUE TITLE
Some improvements for the app: storing search terms, store view counts, add '\n \t' to descriptions, notifications for users

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#114]
Credit to @distalx for pointing out that we could make these improvements: 

-we are not storing search terms, we should. (whenever user search something it should end up in our database for feature optimisations) 
-we also should also store the view counts for each hangouts.
-for description we are storing everything as string - we should store `\n \t`
-notification for users, (whenever someone join or show their intreats in your hangout a respective person should be notified).

**Comment by billglover** [comment]
It looks as though most of these features have been implemented. The only outstanding feature is the proposal to store user search terms. I've raised this feature request as a separate issue #1121 and am now closing this.
