### ISSUE TITLE
Put Netlify logo onto README.md

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#1142]
Netlify has sponsored CodeBuddies with an open source plan!

We need to put their logo on our README.md, on our future site, and on main repo for v3 when it is more active. 

![image](https://user-images.githubusercontent.com/4512699/66627175-ba5d6d80-ebaf-11e9-8a78-554e3e8a4987.png)

**Comment by wait-what** [comment]
I'll do this

**Comment by lpatmo** [comment]
I've added this to README on the `staging` branch.

**Comment by lpatmo** [comment]
Netlify sent out a new form (to be completed March 2020) that requests a link to Netlify be on the main page, so I am reopening this issue.

The form: https://opensource-form.netlify.com/
