### ISSUE TITLE
Can't sign in to Codebuddies.org via GitHub oauth

### ISSUE THREAD

**Issue by brylie** [codebuddies/codebuddies#1148]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
I am unable to sign in to codebuddies.org.

What is the expected behavior?
When completing the GitHub oauth flow, I would be signed in to codebuddies.org

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)
Chrome 78.0.3904.108
Kubuntu 19.10

**Comment by praveeno** [comment]
working fine for me, can you check console, if there are some errors there.

**Comment by brylie** [comment]
This may have been a transient bug, as it was reported in 2019.
