### ISSUE TITLE
Map of user locations / "CodeBuddies Local" feature

### ISSUE THREAD

**Issue by PandaWhisperer** [codebuddies/codebuddies#116]
This idea just came up in the `#remote-workers` Slack channel: it would be cool if there was a map (maybe heatmap) of where CodeBuddies users are located in the world. This could be populated from a (optional for privacy) field in the user profile. 

Along with that, a feature to create local, in-person hangouts so CodeBuddies can schedule meetings IRL with other users.

**Comment by adachiu** [comment]
Inspiration could be found here for data viz. http://www.datavizcatalogue.com/

**Comment by abhiii5459** [comment]
Can I look into this? 
@adachiu @PandaWhisperer

**Comment by wuworkshop** [comment]
@abhiii5459 I don't think anyone has looked into this. So go right ahead!

**Comment by billglover** [comment]
Closing this issue as stale. If this feature is still of interest, please open a new issue and include a reference to this issue by including issue number #116 in the description.
