### ISSUE TITLE
Explanation of the #100daysofcode challenge and #todayilearned hashtag

### ISSUE THREAD

**Issue by wuworkshop** [codebuddies/codebuddies#13]
An explanation of the #100daysofcode challenge and #todayilearned hashtag (currently side projects in development by @abdulhannanali and @linda… if you guys want to help let us know in #codebuddies-meta!)

**Comment by foxiae** [comment]
@wuworkshop I was actually thinking about this the other day. In Slack, we can add an automatic response for when someone asks. But also, we can advertise it on the site as part of how members show what they're learning/working on. I'm thinking it can be another snippet on the About page? At least for now?

**Comment by maudem** [comment]
I've never contributed before and I thought this would be a good place to start.

**Comment by billglover** [comment]
Is this issue still open? It is tagged as `needs code review` but unclear what code needs to be reviewed.
