### ISSUE TITLE
Get contributors list from GitHub via GitHub API

### ISSUE THREAD

**Issue by leewaygroups** [codebuddies/codebuddies#151]
I think it would be nice to get contributors list from GitHub repos.

At the moment the list is hard coded. As more people contribute in future, a manual update of this list may be required. This can be eliminated by getting the list dynamically from GitHub.

 Less markup as well in the view.

**Comment by wuworkshop** [comment]
I believe the reason why @lpatmo does it manually is because not all contributions have been done via GitHub. Some members have contributed via Google Hangouts and the Slack group. Also, not all contributions have been code-based contributions.

**Comment by leewaygroups** [comment]
I see. Thanks for clearing that @wuworkshop . I sensed that when I saw that the current list was more than what is in Github. So I thought of getting what's in Github then merge the rest to have a complete list.

Again this brings us back to some what manual list. I'm not sure how nice this is. What do you think?

**Comment by pv2k** [comment]
I am new to open source world and I would love to work on this issue.

**Comment by lpatmo** [comment]
@pv2k Awesome! It's yours if you want to take it. 

Steps:
- [ ] Create a new "Github Contributors" section on the /about page. 
- [ ] Have the section pull in a list of avatars, with each avatar linking to the contributors' Github profile.

If you create a branch in your forked repo, just leave a comment here indicating what you named the branch if you want anyone to look it over before you submit your PR. Thanks!

**Comment by pv2k** [comment]
@lpatmo Thank you, this means a lot to me.

**Comment by camilleriluke** [comment]
@pv2k and @lpatmo https://github.com/kentcdodds/all-contributors might be of interest to you :)

**Comment by pv2k** [comment]
Sorry to mind @lpatmo, can you tell me where should i start???? I've tried to understand the code and understood a bit of it.

**Comment by William-R-Wilson** [comment]
@pv2k what questions do you have? Do you have questions about the app code or the API?  Might be helpful to talk over on slack.

**Comment by camilleriluke** [comment]
@pv2k how is this one going along? If you need any help, please don't hesitate to ask.

**Comment by lpatmo** [comment]
@pv2k Did `meteor reset` help resolve the issues you were facing?

**Comment by pv2k** [comment]
No, it didn't work @lpatmo and i am not able to get any help from google too.

**Comment by camilleriluke** [comment]
I'm posting this here for transparency's sake and maybe it will be helpful to someone else.

---

This was your comment:

> when i am trying to run the  meteor --settings settings-development.json , i am getting the error as:

```
=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
  
  While processing files with stylus (for target web.browser):
  packages/ian:accounts-ui-bootstrap-3/accounts_ui.styl: Stylus compiler
  error: accounts_ui.styl:85:2
  81| }
  82| .btn-Twitter{
  83|     color: white;
  84|     background-color: #4099FF ;
  85| }
  --------^
  86| 
  87| 
  
  fs.exists is not a function
  
  
=> Your application has errors. Waiting for file change.
```

---

It seems to be an issue related with meteor 1.4 (CB is not using 1.4 yet). So please check the meteor version you are using when running CB.

Go into the checkout folder and run `meteor --version` it should return `Meteor 1.3.2.4`

If it doesn't please make sure you delete your `.meteor` folder inside your directory and run `meteor --settings settings-development.json` again.

**Comment by distalx** [comment]
Just a though. 
Instead of using `APIs` - what if we store contributor's details  into a `json` file. it's not going to change that frequently !!?
>Some members have contributed via Google Hangouts and the Slack group. Also, not all contributions have been code-based contributions. - wuworkshop .

**Comment by sergeant-q** [comment]
@distalx how would we populate the `json` file? Would this be a manual process if we're not using an API? Would it be a section/page accessible to administrators of the site/app where they can input/add contributors and their details?

I understand not all contributions are code-based so it does make sense to capture those somehow. Trying to understand how this would be implemented and managed if we are not looking to use an API.

**Comment by distalx** [comment]
Adding/maintaining  list of the contributors will be manual process, we will maintain a `json` file containing details of contributors , and those who've made a positive impact on the project and the community. 
format could be ...
```
//awesom-pps.json
[
  {
     name: 'xyz',
     avatar: 'http://link or gravater',
     intro: 'lorem ipsum',
     social:[
         {website: 'URL'},
         {twitter: '@handel'},
	 ....
     ]
  },
   ....
]

```
Also this information is not going to change frequently, so having entire `CURD` operation around it would only increases the roundtrips to the server and code/maintains debt. And rendering data from `json` is a fairly simple process in `blaze`.

**Comment by nalbina** [comment]
Is this being worked on?

**Comment by distalx** [comment]
@nalbina nope, feel free to take a jibe at it.

**Comment by billglover** [comment]
Closing this issue as stale. If this feature is still of interest, please open a new issue and include a reference to this issue by including issue number #151 in the description.
