### ISSUE TITLE
Sort list of hangouts on home page by start_at date, not created_at date

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#168]
We should order the list of hangouts on the home page by start_at date so that they're easier to browse.

Also, all "currently happening" hangouts should be at the top of the list.

```
<div>Currently happening</div>
<div>All upcoming or completed hangouts sorted by start_date</div>
```

**Comment by lpatmo** [comment]
@leewaygroups I pushed up a commit to `issue-168-sort-hangout-by-start-at-date` that sorts the hangouts by start_at date. I also merged in the latest changes from master. Please `git pull` in the branch!

A related issue: @distalx pointed out to me that we'll be using up a lot of memory getting each hangout if there are more than a dozen people on the site. We can lessen the chances of the site crashing with high traffic if we:

1) separate out the "completed" hangouts into a separate URL path (e.g. codebuddies.org/completed) that you can get to if you click on a "Browse all completed hangouts" link at the bottom of the list.
2) ONLY show the upcoming and "in progress" hangouts.
3) Load 8 hangouts each time, and only load more if the user clicks to load more. Right now we're loading ALL the hangouts initially and showing 8 at a time.

I can open up a new issue for those three points above, or we can keep the work in this branch.

**Comment by lpatmo** [comment]
Update: the hangouts on production are now sorted by scheduled_at date! I will put the rest in a separate bug.

**Comment by lpatmo** [comment]
Thanks @RuubixO! I will reopen this issue.

**Comment by billglover** [comment]
I'm removing the assignment to @leewaygroups as this was done before the issue was re-opened. It also looks as though upcoming and past hangouts are now sorted correctly and so I'm marking this as closed.
