### ISSUE TITLE
The 'Load More' button under Join Hangouts is a bit aggressive.

### ISSUE THREAD

**Issue by duffbuster** [codebuddies/codebuddies#327]
I want to add a button class called `no-outline` that sets `outline: none`. I found the outline on the load more button mildly annoying.

**Comment by Kartikkh** [comment]
Hey is this feature still needed ?
actually, this would be my first contribution. so if this is needed ! let me give this opportunity .
Thanks

**Comment by lpatmo** [comment]
@Kartikkh I wasn't sure if @duffbuster had been interested in taking this on since he filed this issue, but if not, then you're welcome to it!

**Comment by duffbuster** [comment]
@lpatmo Yeah I just created this issue to jump into stuff. I'll submit a PR.
