### ISSUE TITLE
Implement a tagging system

### ISSUE THREAD

**Issue by Oliver84** [codebuddies/codebuddies#34]
I'd like to be able to add tags to my hangouts so that someone can easily filter through the hangouts and find any relevant hangouts quickly. So if a user wants to see any JavaScript related hangouts, he/she can just click on the JavaScript tag and it'll show all the hangouts that have the JavaScript tag. The tags could be listed inline right under the host, time, and status information of each hangout. 

In about a year or so, when we have 1,000+ active hangouts at a time, this will come in handy! ;-)

**Comment by lpatmo** [comment]
We might not need a tagging system anymore if Ada's mockup gets realized -- where people can search for keywords. 

What do you think?

**Comment by adachiu** [comment]
@lpatmo Would the search need keyword tags to search through? or does it just search through all of the description and title to find the specific keywords?

**Comment by lpatmo** [comment]
@adachiu It should search through all of the descriptions and titles. Have to do more research on which method is easier...

**Comment by adachiu** [comment]
@lpatmo The Meteor Elastic Search looks good!

**Comment by wuworkshop** [comment]
@lpatmo what about this package? https://atmospherejs.com/matteodem/easy-search

**Comment by lpatmo** [comment]
I'm going to move the search discussion out into a different issue, in case we want to revisit implementing tagging.

**Comment by distalx** [comment]
So, tagging system is a go or no go?

**Comment by lpatmo** [comment]
Punting this because we have search, and also (coming soon) the ability to organize hangouts by study group. 

We might reconsider implementing a tagging system if the traffic for hangout increases a lot, and it's harder to search for relevant hangouts. But I don't think this feature is priority now.

**Comment by billglover** [comment]
I'm going to propose closing this issue due to its age. Any objections?

**Comment by lpatmo** [comment]
> In about a year or so, when we have 1,000+ active hangouts at a time, this will come in handy! ;-)

lol.

> I'm going to propose closing this issue due to its age. Any objections?
Thanks Bill! Closing.

**Comment by lpatmo** [comment]
(For the record, we have study groups a pretty good search now.)
