### ISSUE TITLE
Require that users are logged into the CodeBuddies Slack when they sign in with Slack

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#370]
If a user signs in with a Slack team other than codebuddiesmeet.slack.com, they should be redirected to a page (or a popup?) that asks them to sign in with codebuddiesmeet.slack.com, or to join the Slack community if they don't already have an account.

![screen shot 2016-10-26 at 8 33 41 pm](https://cloud.githubusercontent.com/assets/4512699/19753736/1b5bb75a-9bbc-11e6-97ac-9330807e6a83.jpg)

The steps involved:
- [ ] identify if a logged-in user is not signed in to the CB team
  This might be helpful:
  `logged_in_using_codebuddies_team: function() {
  13      if (!(Meteor.loggingIn() || Meteor.userId())) {
  14        return Meteor.user().profile.team_id === Meteor.settings.team_id;
  15      }
  16    }`
- [ ] If their Meteor.user().profile.team_id doesn't match up with `T04AQ6GEY`, instead of seeing the list of hangouts, they should be redirected to a page that contains a message asking them to sign in with the correct Slack team, and to sign up with the CB team on Slack if they don't have an account already.

**Comment by foxiae** [comment]
@lpatmo I'll take a look at this a bit later today.

**Comment by sergeant-q** [comment]
@foxiae are you still tackling this issue?

**Comment by billglover** [comment]
I'm closing this issue as stale. If this issue persists, please open a new issue and reference #370 in the description.
