### ISSUE TITLE
Graph of hangouts vs. learnings count in a timeline

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#38]
Would be cool to see this on the profile page. :)

**Comment by pdotsani** [comment]
[Highcharts](https://atmospherejs.com/highcharts/highcharts-meteor) would be a good library to use if we don't have one installed already.

**Comment by pdotsani** [comment]
@lpatmo what kind of chart are you thinking for this? If it's ok to install highcharts, here are a few [examples](http://www.highcharts.com/demo) to choose from.

**Comment by lpatmo** [comment]
@pdotsani Hmm, good question. (I don't have any preference.) @adachiu, do you have any preferences? (Since you came up with the idea in the mockup.)

**Comment by adachiu** [comment]
@lpatmo I believe we discussed about a Github-like streak graph for learnings. 

For hangouts, it could be a timeline, but do we need it? The profile page already has a list of hangouts that are upcoming or completed. It might become redundant if we have the original list of hangouts on profile page and another timeline showing the same data.

**Comment by billglover** [comment]
Closing this issue as stale. If this feature is still of interest, please open a new issue and include a reference to this issue by including issue number #38 in the description.
