### ISSUE TITLE
Figure out a way to save/archive Etherpad notes from Jitsi

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#449]
On Jitsi hangouts, we can open up an etherpad notepad and get its URL (or iframe embed HTML) and paste it somewhere. 

The downside: the notes are hosted on jitsi's servers.

Ideally, we'd be able to grab the contents and push it to our own site.

**Comment by billglover** [comment]
Closing this issue as stale. If this feature is still of interest, please open a new issue and include a reference to this issue by including issue number #449 in the description.

Additional considerations if re-opened:
- It is possible to export Etherpad documents as Text or HTML.
- How frequently are the Etherpad sessions used?
- Code editors increasingly support shared coding sessions, do these meet the desired goal?
