### ISSUE TITLE
CodeBuddies Staging Site: Screensharing sometimes not working in Safari

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#451]
Can folks confirm that screensharing is not working in some cases in a Jitsi hangout, and paste the console error message here if they see it? 

Jitsi hangout test link (sign in with your CodeBuddies Slack account and RSVP, then click the green button to load the hangout): https://codebuddies.herokuapp.com/hangout/gAexvBQMdXAC4oagh

So far I've only seen this in incognito browsers (which is okay... we'll just not use incognito browsers), but I've also seen it a couple of times in `Safari`.

**Comment by lpatmo** [comment]
This is the error message I saw in Safari when I loaded the Jitsi hangout on https://codebuddies.herokuapp.com/hangout/gAexvBQMdXAC4oagh :

![screen shot 2017-02-11 at 11 43 41 pm](https://cloud.githubusercontent.com/assets/4512699/22860477/f898dc32-f0b3-11e6-9578-d7047d16f6ea.jpg)

**Comment by lpatmo** [comment]
Happens in Chrome too. Figured out that the cause might be related to trying to screenshare in Jitsi initially via an iframe *versus* in a http://jit.si/example link.

I filed this issue here: https://github.com/jitsi/jitsi-meet/issues/1315

**Comment by lpatmo** [comment]
Update: this issue is partly solved for Chrome in the beta version (beta.meet.jit.si). Also, in the beta version, strings with hyphens aren't allowed, so are hangouts will have to be titled `cb[post-id]` instead of `cb-post-id`. Have committed this change in branch `issue-364`.

**Comment by lpatmo** [comment]
Update: screensharing is fine with `beta.meet.jit.si`in Chrome and Firefox.

The remaining issue: Safari and (I assume -- haven't tested yet!) -- IE. 

According to http://lists.jitsi.org/pipermail/users/2016-October/011873.html, the issues with screensharing were known as of October 2016. 

Am considering detecting the user's browser on the page, and recommending that they use Chrome or Firefox.

**Comment by lpatmo** [comment]
According to https://github.com/jitsi/jitsi-meet/issues/1318, screensharing not working on Safari is a known issue.

Idea: detect if a user is NOT on Chrome or Firefox, and suggest that they use Chrome or Firefox. Otherwise, do not show the warning.

**Comment by lpatmo** [comment]
This is done: 
![screen shot 2017-02-15 at 1 07 41 am](https://cloud.githubusercontent.com/assets/4512699/22967413/3e99e1fe-f31b-11e6-9259-5449161fd4ec.jpg)

**Comment by billglover** [comment]
I'm closing this as a known limitation with Jitsi. Safari lets you open the hangout but you are presented with a warning. Screen sharing is not a support feature.

https://web-cdn.jitsi.net/meetjitsi_3216.76/static/recommendedBrowsers.html
