### ISSUE TITLE
Add second-by-second countdown to text on green button on hangout post page

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#453]
It would be cool to see a second-by-second countdown on the green button here:

![screen shot 2017-02-15 at 2 18 38 am](https://cloud.githubusercontent.com/assets/4512699/22969954/29e7cb9a-f325-11e6-8783-c0064b179c30.jpg)

Then, when the hangout starts, the button text will change from the countdown to  say (as it does now) "Click to load hangout":
![screen shot 2017-02-15 at 2 19 41 am](https://cloud.githubusercontent.com/assets/4512699/22969979/44092f0a-f325-11e6-97ee-fe044d5689c1.jpg)

**Comment by lpatmo** [comment]
Update: 

We should continue to display the Jitsi hangout even after the time for the hangout ends, because hangouts often run long, and we don't want to boot users out when the page updates.

 With the soon-to-be-deprecated Google Hangouts API, it was always opened in a separate window, so we didn't really run into this issue.

This means that in the future, anyone will be able to load the Jitsi hangout as *soon* as they RSVP to the event. 

Luckily, having this javascript countdown at the top can make it clear that the hangout has not started yet.

**Comment by valishah** [comment]
Hi @lpatmo . As per my understanding , After opening the post page instead of "Click to load hangouts " we should check the time that the hangout is scheduled for and show the timer accordingly. Can i take care of this ?

**Comment by rmorabia** [comment]
@lpatmo Is this still an issue? Any general update on how you want to tackle this (1 year later)?

**Comment by lpatmo** [comment]
@rmorabia Thanks for pointing this out! I will close it. Not much of a priority issue anymore, since we have a static countdown at the top of hangout pages now (see screenshot below). However, if someone wanted to tackle it, I wouldn't be opposed. Here is an approach I might take: https://codeburst.io/a-countdown-timer-in-pure-javascript-f3cdaae1a1a3

![image](https://user-images.githubusercontent.com/4512699/46546714-c157ee80-c87e-11e8-87b2-74dfbed1b07d.png)

> We should continue to display the Jitsi hangout even after the time for the hangout ends, because hangouts often run long, and we don't want to boot users out when the page updates.

This has been fixed in another PR sometime in the last year.
