### ISSUE TITLE
Add support for logging in using Github authentication

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#457]
Slack sign-in often confuses users, because if you're not logged into any Slack account, you have to remember to type in `codebuddies`.slack.com and then remember your login to that Slack account. 

If we add support for Github authentication, we'll have to make sure to at least get the following fields from the Github API:
- user's email
- user's username
- user's avatar image URL

**Comment by newswim** [comment]
I really like this idea, it's been confusing for myself and others in the past. ++

**Comment by sergeant-q** [comment]
@lpatmo I might have time to take this feature on. Any other specific requirements for user info and are we adding this auth strategy in addition to Slack?

**Comment by lpatmo** [comment]
Cool! Thinking about it a little more, the minimum info. we need from Github are:
- username
- email
- avatar image ("image_192")

And yeah, we're adding this as an auth strategy in addition to Slack, not replacing Slack.

One possibly tricky thing that just occurred to me: `username` assumes a Slack username aka

```
{{# if userInfo.username }}
                  <a href="https://codebuddies.slack.com/messages/{{userInfo.username}}/" target="_blank">
                    <i class="fa fa-slack" aria-hidden="true"></i>
                  </a>
                {{/if}}
``` // profile.html

... so we may have to edit the logic to check for a `userInfo.slack` and make sure that we have a data key named `slack` in our mongo record. 

And we may need to double check that we're not conflating 'username' with Slack usernames elsewhere, as well.

If that doesn't make sense, let me know! Happy to also file a separate issue about it to separate out the steps.

**Comment by lpatmo** [comment]
Backing up a step:
### Disadvantages of supporting Github signin:
- Slack signin usernames will be lost, AKA no way to tie it to a Github login 
- Would be hard to tell who is who on the site, since much of the community/activity exists on Slack (but then again: what if the community moved to the site? Or to a Discourse forum with Github login?)

### Advantages of supporting Github signin:
- easier signin compared to the two-or-three-step process required with Slack

===
Or maybe we simply need clearer instructions about how to log in using Slack? (That is its separate issue already in https://github.com/codebuddiesdotorg/codebuddies/issues/466).

**Comment by nalbina** [comment]
Can't we offer both options at the same time? I know that we could use accounts-github for the github stuff and leave slack like it is?

**Comment by lpatmo** [comment]
@railsstudent and @distalx finished up this issue in https://github.com/codebuddies/codebuddies/pull/802 and https://github.com/codebuddies/codebuddies/pull/811.
