### ISSUE TITLE
Update FAQ with screenshots showing how to log in using Slack

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#466]
1. Update "How do I use this website?" to say "How do I login to this website?"
2. Add the following screenshots:
- A screenshot of the "Sign in with Slack" button
- A screenshot of what you see if you are already logged in to codebuddies.slack.com on your browser
- A screenshot of what you see if you're NOT logged into codebuddies.slack.com, and instructions to type "codebuddies" as the Slack team you're supposed to be logging into
- A screenshot of the authentication screen you'll see after you've signed in, which you have to click to authorize to formally log in

A lot of newcomers seem to get confused about how to log in using Slack, since the site is pretty unique in that it uses Slack-only authentication. 

We have another open issue to allow Github login, but for now let's make it clearer/easier on folks logging in for the first time.

**Comment by dantesolis** [comment]
hey @lpatmo I can take care of this, is no one has claimed it.

**Comment by lpatmo** [comment]
@dantesolis Thank you, I'll mark it as claimed! Let me know if you have any questions...

**Comment by xianrusso** [comment]
Hey @lpatmo , has the issue been resolved?

**Comment by lpatmo** [comment]
@xianrusso Sorry for the slow reply! This issue hasn't been resolved yet. @dantesolis I'm going to mark this as un-claimed again, but if you're interested in it still let me know. Thanks!

**Comment by dantesolis** [comment]
@lpatmo I'm still interested in this issue sorry that is taking me so long, can I claim it again please.
Thanks

**Comment by lpatmo** [comment]
@dantesolis Sure!

**Comment by dantesolis** [comment]
thanks @lpatmo I'll work on it this weekend.

**Comment by labanch** [comment]
Hello @lpatmo, has this issue been resolved? If not, I'd like to give it a go.

**Comment by lpatmo** [comment]
@dantesolis @labanch Do either of you still want to take on this issue (creating a couple of screenshots and adding them to an answer in the FAQ)? Let me know if you have questions!

**Comment by dantesolis** [comment]
@lpatmo sorry yes, I would like to claim it and I'll work on it this weekend. Sorry for the slow replay and slow working on it.

**Comment by lpatmo** [comment]
Thanks @dantesolis!

**Comment by lpatmo** [comment]
@dantesolis Do you have any questions about the issue?
