### ISSUE TITLE
Remind participants to share what they learned at the end of a hangout

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#502]
### Do you want to request a feature or report a bug?
Feature!

### What is the current behavior?
![screen shot 2017-04-22 at 10 58 03 pm](https://cloud.githubusercontent.com/assets/4512699/25311196/40dc6c8e-27af-11e7-9ec9-38bf429e716d.jpg)

### What is the expected behavior?
It might be beneficial to see another "What did you learn?" textarea in the area near or below the "This hangout has ended" text that prompts the attendee to share what they learned.

**Comment by billglover** [comment]
Closing this issue as stale. If this feature is still of interest, please open a new issue and include a reference to this issue by including issue number #502 in the description.
