### ISSUE TITLE
Forum (Discourse)

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#551]
Suggested by @sergeant-q: a forum.codebuddies.org, hosted using Discourse. 

Relevant: https://www.digitalocean.com/products/one-click-apps/discourse/

Question for folks: 
1) Would you join?
2) What categories/tags should we have on the forum? (e.g. AMA, Jobs, Coding-Help, etc.)

**Comment by sergeant-q** [comment]
A few more benefits to highlight: 

- saved chat/discussion history 
- easily searchable data
- topic based discussions ( great for knowledge sharing. Focused and organized discussions)
- CB will own the data and saved long-term 
- Better sense of community and engagement 
- Continue to grow the amazing community our members have helped build to share and teach their knowledge in a friendly environment

**Comment by angelocordon** [comment]
Questions:

+ Would having a separate forum pull people away from the Slack channel?
+ Would core members of the community feel overwhelmed with having to cultivate the community in two separate platforms?

For what it's worth, I don't necessarily think it's a bad idea nor am I a huge member of the community so I don't have much weight on this :) Just wanted to throw out some thoughts out there so that we as a community can cover as much of our bases that we can think of.

**Comment by lpatmo** [comment]
Those are legitimate questions, @angelocordon! Thanks for contributing your thoughts. Here are my opinions:

> Would having a separate forum pull people away from the Slack channel?

Possibly, but I think Slack still gives us the benefit of immediacy and private DMs, which Discord lacks. We're definitely not proposing a full-scale migration from Slack to Discord, but there might be benefits to having a space where our data will be better archived (since we'll own it, instead of having to pay a lot of money to access the archival history). I anticipate that there might be some questions/discussions that'll start naturally appearing more on Slack, and vice versa. (I might be totally wrong, of course! Won't know for sure until we test it out.)

As @sergeant-q mentioned, we often see newcomers ask the same exact question about resources every couple of weeks on Slack; instead of answering them every time, we could share with them the appropriate thread on the Discord forum. 

There's a Discourse -> Slack official plugin that we can install, but no support for Slack posting to Discourse yet: https://meta.discourse.org/t/the-official-discourse-slack-plugin/51412/46

> Would core members of the community feel overwhelmed with having to cultivate the community in two separate platforms?

That's very possible! Maybe there's a way to organize the Discord labels so only discussions of a certain type get posted (aka it's more archival in nature)... ideas welcome.

**Comment by lpatmo** [comment]
Another thought is: there are quite a lot of people who just don't seem to click with the idea of using Slack; they'll join, and never return. And so maybe these folks will like a forum better (or at least get more benefit out of being able to read archives). And maybe we'll end up with primary Slack-focused users, primary forum-focused users, and primary-hangout participants. Just guessing!

**Comment by lpatmo** [comment]
forum.codebuddies.org is now a thing.

A couple of notes:
- Hosting Discourse on DigitalOcean requires a minimum of $20/month.
- The screenshots on https://www.digitalocean.com/community/tutorials/how-to-use-the-discourse-one-click-application-on-digitalocean are a little outdated; there is a "one-click apps" tab in DigitalOcean that you need to select when you are creating the droplet.
- https://www.sparkpost.com/docs/integrations/discourse/ was helpful. Specifically, the line `- exec: rails r "SiteSetting.notification_email=noreply@your-sending-domain.com"` needed to be uncommeted and edited in `/var/discourse/containers/app.yml`, since I did not have `forum.codebuddies.org` configured as a sending domain in Sparkpost. (In other words, needed to change it to `noreply@codebuddies.org). Also, here is how to rebuild the Discourse container while ssh'ed into the DigitalOcean droplet:
```
cd /var/discourse
./launcher rebuild app
```

**Comment by nalbina** [comment]
Will this be properly advertised, integrated?

**Comment by lpatmo** [comment]
No one's really had time to work on it, but @kvie (on Slack) is interested in looking at it and possibly taking the lead on figuring out how we can use Discourse the best way! An API key expired, so I have to figure that out (possibly rebuild the whole thing) before I can invite her to it.

**Comment by nalbina** [comment]
Now that we have discussions can this be closed?

**Comment by sergeant-q** [comment]
https://forum.codebuddies.org is now live (again) and hopefully staying for good. @lpatmo can we close out this issue?
