### ISSUE TITLE
Is it possible to have automatically triggered builds for new branches on forked repos? (CI for forked projects)

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#561]
Came up in discussion during Labor Day sprint hangout. It'd be nice if branches contributors pushed up triggered an automatic build of tests. cc @sergeant-q

**Comment by billglover** [comment]
Closing this issue as stale. If this feature is still of interest, please open a new issue and include a reference to this issue by including issue number #561 in the description.
