### ISSUE TITLE
STUDY GROUPS: Downvoting learnings should have a different icon, color, or cue

### ISSUE THREAD

**Issue by osanseviero** [codebuddies/codebuddies#588]
Maybe making the icon red?

<img width="675" alt="screen shot 2017-09-10 at 21 47 56" src="https://user-images.githubusercontent.com/7246357/30258879-f1b1c7bc-9671-11e7-91c5-42d8656e132f.png">
<img width="674" alt="screen shot 2017-09-10 at 21 48 09" src="https://user-images.githubusercontent.com/7246357/30258880-f1c5fdb8-9671-11e7-8fe8-a50cf75f5009.png">

**Comment by dantesolis** [comment]
I could also pick this one up as well, if it hasn't been claimed 😀

**Comment by lpatmo** [comment]
@dantesolis Thanks, I will mark this as claimed!

**Comment by dantesolis** [comment]
@lpatmo hey guys still working on this. I should be sending a  PR  in the following days.

**Comment by ArhantJain** [comment]
I'm interested in tackling this as a part of Hacktoberfest.Where might I take a look for this?

**Comment by dantesolis** [comment]
@ArhantJain , I was tackling this, but I'm working on two others, so please take it. Many different ways to do it:

- you could change the color on the icon after it has been toggled; (the quickest) (check: `_status_list.scss`)
- you could also do it with js  and add an down arrow icon; (a bit more time) (check: `learning-item.js, status-item.js`);

**Comment by lpatmo** [comment]
Marking this as unclaimed again, since it's been a year!

**Comment by TomerPacific** [comment]
@lpatmo ,
I would like to take this issue. Let me know if it is possible.

**Comment by lpatmo** [comment]
@TomerPacific Thanks, go ahead! I haven't looked into the specifics of the fix, but let me know if it's not straightforward, since it's more a `nice-to-have` rather than a priority issue. :)

**Comment by TomerPacific** [comment]
@lpatmo ,
I have a development environment running and I have read the comments above and their suggestions on how to fix this issue. I have two things I want to know:

1. How can I see a real world example of this issue (without joining a study group)? Tried to find the Learnings section, but came up short.

1. In the development environment, there are no study groups, so I was wondering how, when I will fix this issue, I can simulate it to see that everything is working?

Thanks

**Comment by lpatmo** [comment]
@TomerPacific You can create a study group in localhost:3000 and write a learning inside it. On the localhost:3000/hangouts page, you should also see learnings on the sidebar, so you can save a test learning and see the upvote/downvote buttons there too.

Similarly, you can create a study group at localhost:3000/study-groups. 

In terms of seeding test hangouts/groups... I don't remember if this is documented in docs.codebuddies.org, but if you change `  "seeder": false,` to true in settings-development.json before running `meteor reset` and start up the app again, I think that will seed test hangouts at least.

Hope this helps! Let me know if you have questions still.

**Comment by lpatmo** [comment]
@TomerPacific Thanks! 

Re: signing in -- signing in/signing up using Github will also work. :) Let me know if it didn't or if it wasn't clear that it would. 

Re: down arrow -- I'm thinking we should only have it appear after a user has already upvoted once, since generally we want to applaud learnings and let people undo their upvote only if they hadn't intended to.

**Comment by TomerPacific** [comment]
I have opened a [PR](https://github.com/codebuddies/codebuddies/pull/1040)
