### ISSUE TITLE
Design Request: Contrast of Hangout Tips text

### ISSUE THREAD

**Issue by osanseviero** [codebuddies/codebuddies#594]
The current text in hangouts tips is a bit hard to read. It's also an a11y issue.

<img width="325" alt="screen shot 2017-09-12 at 23 00 19" src="https://user-images.githubusercontent.com/7246357/30361885-36ff07f6-980e-11e7-8a51-15c260fc9631.png">

The two ways to go are:
- Increase the contrast
- Increase the size

Or both.

The "silent hangout  started by" text is a bit hard to read as well.

**Comment by osanseviero** [comment]
This is the full screen
<img width="1278" alt="screen shot 2017-09-12 at 23 02 25" src="https://user-images.githubusercontent.com/7246357/30361950-79b245f4-980e-11e7-932c-c3c34628650f.png">

**Comment by dantesolis** [comment]
@osanseviero & @lpatmo, I can pick this up if hasn't been claimed.

**Comment by lpatmo** [comment]
@dantesolis If you're still interested in working on it, it's yours! Otherwise I will mark it as un-claimed again.

**Comment by dantesolis** [comment]
@lpatmo still interested in working on it :). I'll be sending something on the following days.

**Comment by lpatmo** [comment]
@dantesolis Sounds good! Just let me know if you'd like to pass it off to another person. I've added the `Hacktoberfest` label to this issue, if you've signed up for Hacktoberfest, this can count as one of your four PRs. :)

**Comment by dantesolis** [comment]
@lpatmo sorry I've been a bit busy with some personal stuff, but I should be sending that PR by the end of this week.

**Comment by lpatmo** [comment]
Un-marking this as claimed. Help wanted once again!

**Comment by dantesolis** [comment]
@lpatmo may I claim this one again please? Thanks

**Comment by lpatmo** [comment]
@dantesolis Yep!

**Comment by dantesolis** [comment]
@lpatmo thank you for this!!! 👍

**Comment by distalx** [comment]
@dantesolis  could you give us an update? Thanks.

**Comment by dantesolis** [comment]
@distalx this is right now on a [PR-714](https://github.com/codebuddiesdotorg/codebuddies/pull/714)
