### ISSUE TITLE
Remove 140-character limit on learnings and support code markdown (or WYSIWG)

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#642]
Within each study group on http://staging.codebuddies.org/study-groups, we have a textbox that lets users share what they learned or accomplished. 

![screen shot 2017-10-06 at 1 13 27 am](https://user-images.githubusercontent.com/4512699/31269058-c3491d6e-aa33-11e7-93ad-697e99536670.jpg)

Right now the message is limited to 140 characters, but 140 characters is too limiting if I'm pasting in code snippets.

Ideally, we'd support the same single or triple backticks commonly used on Slack (```) and (`). 

We've used QuillJS for our WYSIWG elsewhere -- for example, on the create-a-hangout modal. Not sure if we should use QuillJS here as well, or use Meteor's native `markdown` package: https://docs.meteor.com/packages/markdown.html. What do folks prefer?

**Comment by distalx** [comment]
@lpatmo, 140 character limit is there because we are twitting these learnings via `codebuddiesmeet` twitter account.  removing character limit might brake that functionality.

We should create a new collection for managing process logs, and it would be nice to have WYSIWG in place.

**Comment by lpatmo** [comment]
It'd be nice if the tweets linked back to the original post, instead of being self-contained. But that would require each learnings post having a clickable URL to go to. 

If we create a new collection for managing progress logs, we wouldn't be using the `learnings` collection anywhere anymore, would we?

**Comment by distalx** [comment]
I’ll look into it.
