### ISSUE TITLE
Finish Site Documentation for Future Contributors at docs.codebuddies.org

### ISSUE THREAD

**Issue by oliikit** [codebuddies/codebuddies#72]
To ensure the site is well-maintained, we should look into documenting code structure, design principle, user functionality, etc. 

From Slack, @lpatmo suggested a FAQ knowledge base, @adachiu suggested a style guide, and @William-R-Wilson suggested a code style guide (e.g., code organization/file structure, variable naming, tabbing).

@distalx mentioned we could use `@comments` to generate documentation and other npm packages (e.g., https://www.npmjs.com/package/apidoc).

@adachiu mentioned http://patternlab.io/ for design documentation.

What documentation should we provide for future contributors? How should we go about it?

UPDATE: http://docs.codebuddies.org is now the official home for documentation. Help wanted: https://github.com/codebuddiesdotorg/documentation

**Comment by distalx** [comment]
This package might be useful for doc genaration.
https://www.npmjs.com/package/meteor-jsdoc

**Comment by sergeant-q** [comment]
**JSDocs** is the de facto or **go to** for documenting Javascript files and follows a good style and convention used by the community.  Going with this package seems like a good fit!

**As a side note**: this also means we should encourage and will have to refactor our codebase to properly document our code following this convention.

**Comment by foxiae** [comment]
If JSDocs is what we should go with, I can look into the implementation over the weekend.

Does anyone know of an automated JS code reviews to catch styling issues for our current code base? I know rails has the gems robocop and pronto.

**Comment by wuworkshop** [comment]
I haven't used DocumentCSS, but this article makes it sound pretty sweet.

http://blog.bitovi.com/style-guide-driven-development/

The article also mentions this nice list of style guide generators:

https://github.com/davidhund/styleguide-generators

**Comment by distalx** [comment]
This is a nice approach for style guide
http://rscss.io/

**Comment by foxiae** [comment]
@wuworkshop, @distalx thanks for the sites! I'll make some sample docs over the weekend from these resources, and we can see what would work best.

**Comment by foxiae** [comment]
So I was able to check out a lot of style guides over the weekend. I think [SCS Style Guide Generator](http://styleguide.sc5.io/) will be the best. Working with nodejs is still really new to me, so it's taking me awhile to read up on how to implement it.  For the jsdocs,I just need to add/format already existing comments to have something to show.

@distalx, the RSCSS site is really good. And should we refactor our CSS code, it would be a good guideline.

**Comment by foxiae** [comment]
At this time, I'm going to put this issue on hold. Most frontend styleguides use gulp/grunt to get everything working, which, as I have learned, isn't that easy to implement with meteor. 

With the implementation of 1.3, we can introduce Meteor's recommended [code style](http://guide.meteor.com/code-style.html). They recommend using Airbnb styleguide for both JS and CSS. ESLint will also work in 1.3 to check user's code against the styleguide (which may be good to have as more new comers come onto the project). If we feel like we should have a JSdoc, we can also implement it at that time.

I'm not sure if 1.3 will make it easier to implement a frontend styleguide, but I'll relook when I get more familiar with 1.3.

**Comment by sergeant-q** [comment]
I think the style guide recommended by Meteor (Airbnb) is what we should definitely shoot for. Once we migrate the project to **1.3** we can probably take advantage of this NPM package or something similar to generate the actual docs for our site. 

https://www.npmjs.com/package/meteor-jsdoc

**Comment by distalx** [comment]
For project documentation with Markdown.
http://www.mkdocs.org/

**Comment by foxiae** [comment]
Just an update on this. Looks like there's some meteor packages available for style guide (https://atmospherejs.com/?q=style%20guidea).

I tried installing [Hubble](https://atmospherejs.com/rhjulskov/hubble) since we are using Blaze, but fourseven:scss was incompatible. I didn't play around with the configuration settings. But if we're moving over to React ([Issue 211](https://github.com/codebuddiesdotorg/cb-v2-scratch/issues/211)), then we can use the [React Style Guide](https://atmospherejs.com/webysr/react-style-guide), which will _hopefully_ be easier to install than everything else I've tried.

**Comment by distalx** [comment]
I think we should start working on this one ASAP, because already we have started repeating code, and templates multiple times. 


>What documentation should we provide for future contributors? How should we go about it?

Documenting a project is a fairly lengthy task so let's break it down into ...

1. coding guidelines and app structure

    for coding guidelines we could use `wiki` pages and we could address/include following things.
    - coding conventions. (I'd suggest we adopted [hapijs/styleguide](http://hapijs.com/styleguide), it's purrrrrfect.)
    - CSS style guide
    - directory structure.

2. database schema (wiki pages)
    description of all the collections. 

3. app documentation 
    use `js-docs` or `meteor-jsdoc` package and generate documentation for app.

**Comment by lpatmo** [comment]
UPDATE: new docs are now at `docs.codebuddies.org`. Please let us know if you'd like to help contribute to it! https://github.com/codebuddiesdotorg/documentation

**Comment by billglover** [comment]
I'm closing this issue as the documentation is live on GitBook and it is not clear what work needs to be done to close the issue. Work on specific sections can be tracked under new issues. Please feel free to reference #72 in the description.
