### ISSUE TITLE
Improve styling of CodeBuddies' reminder/follow-up email templates

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#742]
![image](https://user-images.githubusercontent.com/4512699/34073999-4ad72ac8-e25b-11e7-911c-865b549d3660.png)

![image](https://user-images.githubusercontent.com/4512699/34074002-4ff8e6f4-e25b-11e7-8b37-45b216273d50.png)

![image](https://user-images.githubusercontent.com/4512699/34074003-533f62fc-e25b-11e7-9ad3-ba9d1612d195.png)

H/t @alfougy for finding this bug!

Color schemes are off, so we should improve that. And if the PR submitter has other design improvements, they should feel free to make them.

The four files to edit:
private/email-hangout-alerts.html
private/email-hangout-reminder-two.html
private/email-hangout-followup.html
private/email-hangout-reminder.html

**Comment by xXSupernaturalBuilderXx** [comment]
This is the design I came up with.
![screenshot 2](https://user-images.githubusercontent.com/26035222/34077669-4a9a3376-e2d7-11e7-9e98-f0f8762bf327.png)

**Comment by lpatmo** [comment]
Looks wonderful, @xXSupernaturalBuilderXx!!

**Comment by angelocordon** [comment]
Looks great, I like that it follows the same style as the website. 

My only feedback here is that perhaps we can lose the background on the paragraph text (okay to keep it around the headlines). 

The blue background and the thin font makes it difficult to read.

**Comment by sergeant-q** [comment]
Yes please! My initial roll out of these templates were based off mail chimp default styles. Happy to see they're finally getting the TLC they deserve!

**Comment by lpatmo** [comment]
@xXSupernaturalBuilderXx Could we give the top header ("Hangout Alert") a blue background, but leave the paragraph fonts black and non-bold? And remove the background blue for the container?

**Comment by angelocordon** [comment]
![image](https://user-images.githubusercontent.com/3891869/34133530-238c67de-e40a-11e7-8779-935e4bd7f9cc.png)

@xXSupernaturalBuilderXx - meant for something simpler. Just drafted off what you got :) As these are email templates, it's probably best to keep it simple (they'll probably be coded as tables, and CSS with emails are annoying)  :)

**Comment by angelocordon** [comment]
There's lots of improvements for copy - I just did enough to show what I meant

**Comment by xXSupernaturalBuilderXx** [comment]
Does anybody have any other ideas for improvment that I could possibly make?

**Comment by lpatmo** [comment]
@xXSupernaturalBuilderXx I honestly think the next step is to implement it. If you want, we can tackle this issue together in a hangout/submit the PR sometime! I predict will take 1-2 hours.

**Comment by xXSupernaturalBuilderXx** [comment]
@lpatmo that can work

**Comment by lpatmo** [comment]
Reportback: we worked on it together, and I pushed up a new branch called `issue-742-email`: https://github.com/codebuddiesdotorg/codebuddies/blob/issue-742-email/private/email-hangout-alerts.html

TODO: still need to apply the design upgrades to the other email templates in that `private` folder.
