### ISSUE TITLE
Integrate Slack signups with `mail-for-good` setup (newsletter)

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#746]
See: https://github.com/freeCodeCamp/mail-for-good

Background:
We currently have ~4000 on our tinyletter.com/codebuddies newsletter. Tinyletter offers free sends for up to 5000 subscribers. If we ever end up with more users than we expected after "launching" on HN or something, it'd be good to sign up those additional users to the newsletter. Mailchimp is pricey after a couple thousand users, and FreeCodeCamp's mail-for-good project seems like it would be inexpensive and also a great fit for our needs.

**Comment by billglover** [comment]
This appears to relate to #143

Closing this issue as stale. If this feature is still of interest, please open a new issue and include a reference to this issue by including issue number #746 and #143 in the description.
