### ISSUE TITLE
IDEA: Let study group owners automate hangout announcements to a specific designated channel

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#750]
> Do you want to request a feature or report a bug?

Feature

> What is the current behavior?

Currently, every time a new hangout is scheduled, it gets automatically posted to the #announcements channel, and it's easy for the Slack community to miss them due to other hangouts being scheduled. Ideally, the hangout creator would also post in a specific channel as well -- e.g. the following hangout announcement should also probably be shared in the #python channel:

![screen shot 2017-12-23 at 1 13 40 am](https://user-images.githubusercontent.com/4512699/34317520-b75d18a6-e77e-11e7-8a34-8d6f14c8aac0.jpg)

It takes effort to think about an additional channel to manually paste a link to, though!

> What is the expected behavior?
Let's automate this by giving the study group admins the ability to select a Slack channel that hangout announcements would automatically get posted to. 

For example, the admins of the "CSS for Beginners" study group would see an option under "Settings" that lets them select the "#html-css" channel, and all new hangouts created in this study group would automatically get an alert there.

Opinions welcome on whether:
a) The list of channels should be pre-set (i.e. we'd draw from the public channels available using the Slack API)
b) Whether the option to select a Slack channel to post to should appear in the "Settings" tab on a study group, or in the "Hangouts" tab

**Comment by railsstudent** [comment]
For part a)
1) We can call https://api.slack.com/methods/channels.list lists all public slack channels and populate a select2 dropdown, or
2) Add a new tab or under settings, study group owner/admin/administrator can maintain a list of slack channels and send hangout announcements from the list

For part b, I prefer settings

Hangout announcements should be able to send to multiple slack channels.  If the hangout is about data science in python, members in both channels should be notified. 

My humble two cents.

Thanks.

**Comment by lpatmo** [comment]
Thanks for your input! Agreed on Approach 1.

For part b) though, I'm thinking we may want to cap the maximum number of channels that can be notified (maybe 3? Or 2?) because otherwise it may be all too easy to "spam" multiple channels. Your example re: #data-science and #python sounds fine, but it might get annoying with more than that.

**Comment by railsstudent** [comment]
@lpatmo  Setting a cap on the number of channels is good idea because it avoids possible spamming.  However, some technologies have more related slack channels than others; therefore, 2 -3 may be not enough. For example, there are five JS-related slack channels already.  Allowing only 2 channels means the rest of the channels are omitted.

**Comment by stain88** [comment]
Just because there are 5 js channels doesn't mean the announcement should be posted to all of them - either it's generic enough to go into the main #javascript channel, or it goes in one of the more specific ones.
I think starting with 3 max is enough to allow some cross-channel announcements, and if it becomes obvious that more are needed, we can increase later.

**Comment by railsstudent** [comment]
@stain88  Yeah, I think hangout owner can post the link to specific channels if 3 is not enough.
the max number should be config value is settings.json.  If not specified in the json, default to 3.

Select allows limit selection
$(".js-example-basic-multiple-limit").select2({
  maximumSelectionLength: 2
});
