### ISSUE TITLE
Slack / Community Etiquette Page

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/codebuddies#773]
Propose we have a static web page (codebuddies.org/slack-etiquette) that holds our Slack / Community Etiquette rules.  The link below is a combination of ideas from https://www.reactiflux.com/tips/ and our previous Slack Etiquette doc.  Suggestions and revisions are welcomed.

https://slack-files.com/T04AQ6GEY-F8VRAGD0S-ebfb2269d1

**Comment by lpatmo** [comment]
@aimeerpierce pierce pierce I think if you're logged into the CodeBuddies Slack, you should be able to see https://slack-files.com/T04AQ6GEY-F8VRAGD0S-ebfb2269d1. I don't think we reference it anywhere currently on Slack, actually! And it's not in the repo either. 

Thanks for your interest in tackling this! :) Let us know if you have any questions.

**Comment by railsstudent** [comment]
Claimed by @aimeerpierce

**Comment by wuworkshop** [comment]
@aimeerpierce Hmm... when I click on that link, it just opens in a new browser tab for me. I'm not even logged in to the CB Slack in a browser. I think since it's a public file link, you should be able to just view it in a browser? 🤔
