### ISSUE TITLE
Community Welcome Page

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/codebuddies#774]
Propose a static **"Community Welcome"** page.  Not sure if this should be new copy for the **Home** page, or just a welcome page that we send people to from the Slack channel.  Either way, I think the copy linked below (which is currently a pinned post in the **#start_here** channel in Slack) might need to be re-worked.  The page itself will (obviously) need some design love.

https://slack-files.com/T04AQ6GEY-F8X5U3HRV-d0892dda60

Thoughts / comments / edits welcome.

**Comment by lpatmo** [comment]
Belated update: @julianjohannesen submitted a PR to make https://codebuddies.org/welcome a while back. Closing this issue now. :)
