### ISSUE TITLE
Auto-Email Slack Welcome Message on Signup by New Members

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/codebuddies#775]
Craft code for generating & emailing a custom **_Slack Welcome_** on new user Sign-up.

- [ ] The body of the email will be  a variant of the [attached Welcome message](https://slack-files.com/T04AQ6GEY-F8X5U3HRV-d0892dda60) that is currently in use in the Slack _#start_here_ channel.
- [ ] The email will be triggered on on of the following:
        -  new user signup via the codebuddies.org website, 
        -  personal invite, 
        -  Slack app signup
       -  direct add by an admin or moderator.
- [ ] The email will be sent to the email address provided by the new member when they fill out the Slack new user account info.  Changes to the original address won't trigger a new email.

__________________________________________________________________

A couple of edits will be needed for the text of the email:

-  The **[CHANNELS]** link currently in the doc will need to be replaced with the external link to the Slack Help Doc on browsing channels:  https://get.slack.help/hc/en-us/articles/205239967-Browse-and-join-channels

-  The **[CodeBuddies Slack Etiquette for General Members]** link currently in the doc will need to be replaced with this external link (https://slack-files.com/T04AQ6GEY-F8VRAGD0S-ebfb2269d1) - and ultimately, with a link to a (yet to be done) page on the codebuddies.org website.

**Comment by lpatmo** [comment]
We still don't automatically send out a welcome email to new users after they log in to the site for the first time. 

The contents of the email could be a mirror of what users currently see when on the #landing_pad channel in Slack, as written beautifully by Bethany:

![screen shot 2018-09-27 at 1 28 21 am](https://user-images.githubusercontent.com/4512699/46133136-a63d0d00-c1f4-11e8-94e6-6f22f2bc00bf.jpg)

**Comment by joelmheim** [comment]
I would like to take a stab at this, if it is not already being worked on.

**Comment by lpatmo** [comment]
@joelmheim Thanks, go ahead! Let us know if you have questions.

**Comment by joelmheim** [comment]
Will do. Have started looking into it.

**Comment by joelmheim** [comment]
I have been looking at this, and while I must admit that I've had some problems finding my way in the codebase (mostly because I'm not familiar with Meteor), my plan so far is to somehow trigger email sending from the Accounts.onCreateUser callback that is already implemented. The problem is that there are multiple return statements in this method depending on the login service. Feel we should have a little discussion about how to design this.

I also need some help with where to put the template for the email message. My initial thought is to model it on the emailNotification method on the server, but I can't seem to find where the email templates are located.

Any inputs are appreciated.

**Comment by lpatmo** [comment]
Thanks for looking into this, @joelmheim! A couple of quick thoughts:

- We should send the email welcome message regardless of which service the user signs up with, so like the `SlackAPI.inviteUser(user.email);`, maybe we could have a `

- Templates for existing emails currently live in the `private` folder. One template you could probably copy/paste and fill in the welcome content for: private/templates/email/new_member.html. Here's a screenshot:

![image](https://user-images.githubusercontent.com/4512699/46853554-5abd5e00-cdb3-11e8-8839-29b97472ae06.png)

**Comment by joelmheim** [comment]
Will start putting this into code. I will create an initial suggestion as a pull request, and then we can refine it together before we merge it in. I will make sure the initial version is functional to the extent that I can. Much easier to discuss once we have some code to look at.

**Comment by joelmheim** [comment]
Can you direct me to the code where these templates are used for sending email? Having trouble finding it on my own.

Also, I will start putting together a PR on this. I think it is easier to discuss different options once we have some code to look at. We can do more iterations on it before we merge it, if necessary.

**Comment by joelmheim** [comment]
I think I figured it out. Trying to get a PR in tomorrow or Sunday as a first suggestion.

**Comment by lpatmo** [comment]
@joelmheim Thanks. Re: code involving sending email -- did you find `imports/libs/server/cron/initial_email_notifications.js`? I see a couple of calls to `CBMailer` in there.

**Comment by joelmheim** [comment]
@lpatmo Will you have a look and maybe test the functionality? I'm having problems in dev with wrong login information for the SMTP service, so I wasn't able to test the email sending and look at the format.

**Comment by railsstudent** [comment]
@joelmheim I can send you smtp api id after work tonight.   However, please do not commit it to github. Thanks.

**Comment by joelmheim** [comment]
@railsstudent Great. Appreciate it.

**Comment by joelmheim** [comment]
Tested again now, and confirmed that the email sending is working.  Attached is a PDF of the email I received in test. Happy to work further with you on the format of the email. But the functionality is certainly working. We can also discuss the code itself. As you can see I've made some changes to the main.js file, so it will affect all user sign-in.
[codebuddies-welcome-email.pdf](https://github.com/codebuddies/codebuddies/files/2482121/codebuddies-welcome-email.pdf)
