### ISSUE TITLE
Custom Slackbot Welcome Message as Replacement to Janitr

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/codebuddies#777]
Replace current Janitr integration that welcomes new users with a variant of https://slack-files.com/T04AQ6GEY-F8X5U3HRV-d0892dda60, in a custom Slackbot message.

See https://api.slack.com/best-practices/blueprints/new-user-notification for Slack's How-To
See https://glitch.com/~slack-terms-of-service-blueprint  for a Step-by-step, and hackable boilerplate.

**Comment by BethanyG** [comment]
![screen shot 2018-01-28 at 12 16 43 am](https://user-images.githubusercontent.com/5923094/35480347-baf3cd9e-03c0-11e8-9177-5ecc057994e6.png)

**Comment by BethanyG** [comment]
An additional enhancement of an interactive questionnaire is TBD.

**Comment by BethanyG** [comment]
Should probably close this issue and start tracking enhancements/bugs/fixes in the greetbot repo.  However - I can't seem to turn on issues.  Is that because the dang thing is forked?

**Comment by lpatmo** [comment]
I took a look in the `Options` tab on the greetbot repo and checked the "Issues" checkbox, so issues should now be appearing in that repo!

**Comment by lpatmo** [comment]
~The welcome bot is live already for new users signing up to codebuddies.slack.com! Please see https://github.com/codebuddies/greetbot for new issues regarding the greetbot.~
