### ISSUE TITLE
Hangout Learnings are Auto-Tweeted without Author's Knowledge or Consent

### ISSUE THREAD

**Issue by julianjohannesen** [codebuddies/codebuddies#784]
Do you want to request a feature or report a bug?
Feature

What is the current behavior?
Hangout Learnings are auto-Tweeted without users knowledge or consent

What is the expected behavior?
Users should  be warned that Hangout Learnings are auto-Tweeted and can opt-out of that behavior

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)

**Comment by lpatmo** [comment]
As a first step for implementation, let's add a message below the learnings box to warn users that their learnings will be auto-tweeted to @codebuddiesmeet. 

Next step:
Add a checkbox that -- when checked -- will NOT tweet out the message.

What do you think? Or should the checkbox have the opposite behavior?

**Comment by julianjohannesen** [comment]
I think opting out is fine.

**Comment by julianjohannesen** [comment]
So, if i wanted to add the notification, would I do that in client/templates/hangout/hangout.html or in hangout-learned.html?

**Comment by julianjohannesen** [comment]
Ah. Okay. I missed that one.

**Comment by railsstudent** [comment]
@julianjohannesen  Are you working on this issue?
