### ISSUE TITLE
Add unsubscribe link to automated email reminders

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#787]
We need to add an unsubscribe link to the automated 24-hour hangout email reminder and cancellation notification. #bestpractices 

Ideally, we'd have a page where users can manage their email preferences, but we can do that later.

Note: we may want to integrate this into https://github.com/codebuddies/codebuddies/pull/776.

**Comment by nalbina** [comment]
Are we using a service for sending the emails? Shouldn't they auto-add an unsubscribe link already?

**Comment by distalx** [comment]
I'll take this one.
