### ISSUE TITLE
CSS issue: "Select up to 3 slack channels" message in select box hidden by width of 100px

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#790]
![screen shot 2018-02-11 at 10 00 57 pm](https://user-images.githubusercontent.com/4512699/36085037-8c9d3878-0f77-11e8-9f1c-6e8c26c1a10b.jpg)

You'll land on this screen if you are the owner of a study group, and click on the `Settings` tab within the group.

This is a `good-for-beginners` issues. Docs at docs.codebuddies.org. Please comment if you'd like to work on it, or if you have any questions. Thanks!

**Comment by rmorabia** [comment]
I think I can claim this? It may take me a while since I've never worked with large git projects & Meteor, but I'm going to at least say I'll try?

**Comment by railsstudent** [comment]
@rmorabia  There is a bug in select2 that causes this issue to happen. You can refer to this https://github.com/select2/select2/issues/291 to see the hack people do.  
Or try your own hack to get the width working. Thanks.

**Comment by railsstudent** [comment]
@rmorabia  Please kindly work on it. The first PR is always the sweetest.
