### ISSUE TITLE
force-ssl blocks docker container

### ISSUE THREAD

**Issue by nalbina** [codebuddies/codebuddies#794]
We are using the meteor package `force-ssl`. With that, we can't build docker containers, because it keeps redirecting away from the exposed port.
@distalx What do we use it for and can we possibly remove it and force SSL on the webserver level?

**Comment by Sult** [comment]
Dont know much from the setup (just actively reading some things ) What i do is redirect inside nginx (or apache2 or whatever) every incoming request to https on same url.

**Comment by distalx** [comment]
@nalbina, earlier we were using a heroku as our staging env, where `https` wan't a default behaviour - this package was added to counter that.

We could probably remove that since we are no longer using heroku as a staging env.

**Comment by distalx** [comment]
`force-ssl` is removed in #795.
