### ISSUE TITLE
Increase height of `completed` hangouts to 180px

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#818]
Problem:

![screen shot 2018-04-15 at 3 14 08 am](https://user-images.githubusercontent.com/4512699/38777342-376b044c-405b-11e8-9884-be6dfa9c74ff.jpg)

If we increase the height of these cards in _hangout_card.scss to 180px (or 185px??) instead of 160px, we can clean this up.

This issue is for a first-timer pull requester.

**Comment by WinterCore** [comment]
Hi, May I work on this one ?

**Comment by lpatmo** [comment]
@WinterCore Hi -- yes, sure! Let me know if you have any questions. The docs are at docs.codebuddies.org.
