### ISSUE TITLE
User (hangout host) should not be able to delete an ongoing hangout. 

### ISSUE THREAD

**Issue by leewaygroups** [codebuddies/codebuddies#82]
![cb_issue](https://cloud.githubusercontent.com/assets/7301892/14063480/76410f6a-f3fd-11e5-8dd9-331ba1a710b6.png)

**Comment by lpatmo** [comment]
I'm kind of conflicted about whether this should be a feature.

What if a user creates a teaching hangout (with the expectation that they'll be teaching students), but has to cancel last minute -- or right as the hangout starts?

**Comment by sergeant-q** [comment]
I agree, we should keep this option available at any time. Best case scenario, the host can reschedule the hangout session by _updating_ the hangout.

**Comment by sebbel** [comment]
I would expand the error message if the hangout is live. Something like "Are you positive to leave this hangout? There are people here."

**Comment by leewaygroups** [comment]
@sebbel I think your suggestion is a fine one. Let's see what other's think.

**Comment by billglover** [comment]
Closing this issue as stale. If this feature is still of interest, please open a new issue and include a reference to this issue by including issue number #82 in the description.
