### ISSUE TITLE
Sweetalert: add "sign in with Github" option to popup that user sees when they're not logged in

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#821]
Now that we support logging in with Github, we should add a "Sign in with Github" button here:

![screen shot 2018-04-15 at 3 41 16 pm](https://user-images.githubusercontent.com/4512699/38784216-af99eb5a-40c3-11e8-9216-b849f76c336b.jpg)

**Comment by railsstudent** [comment]
You beat me into submitting the issue.

**Comment by railsstudent** [comment]
@lpatmo @distalx  It seems sweetalert 1.x does not support three buttons in the dialog. Another suggestion to make a custom dialog that renders three buttons? thanks.

**Comment by distalx** [comment]
Should we update to SweetAlert 2?

-----Original Message-----

**Comment by BogDAAAMN** [comment]
Is this issue still unresolved? If so, I'd like to claim it.

**Comment by railsstudent** [comment]
@BogDAAAMN, thanks for showing interest on this issue.  It is not claimed but it depends on @lpatmo and @distalx decision to upgrade sweetalert to v2 or not.
It is because sweetalert v1 dialog does not support more than 2 buttons while v2 can configure to have more than 2 buttons.

However, upgrading to v2 also means than all sweetalert modals need to upgrade.   If you are interested, would you study sweetalert v2 doc to see how it is done and its complexity?
You are welcome to claim it if you are still interested afterward.  I am gladly reassign it to you as I work on another github issue.

**Comment by BogDAAAMN** [comment]
Alright, I'll take a look. Keep you posted.

**Comment by lpatmo** [comment]
For what it's worth, I have no objections to upgrading to v2. Thanks for taking a look, @BogDAAAMN.

**Comment by railsstudent** [comment]
Claimed by @BogDAAAMN

**Comment by sergeant-q** [comment]
@BogDAAAMN what is the status on this issue?

**Comment by railsstudent** [comment]
The person has not started the item for a long time. Are you interested? Thanks.

**Comment by peoray** [comment]
@railsstudent yes I am

**Comment by mahamshahid18** [comment]
Oh alright then. Hey @peoray, if you're not done with it already, let me know if you want to collaborate on it :)

**Comment by peoray** [comment]
Sure, we can. If you are in the slack channel, send me a PM on @peoray

cc @mahamshahid18

**Comment by lpatmo** [comment]
@peoray The popup is generated via sweetalert, in `client/layouts/layout.js`

No preference re: styling; IIRC the tricky thing is getting Github supported.

**Comment by lpatmo** [comment]
@peoray Thanks for poking at me to follow up on this thread. (Sorry I missed this!) To clarify, this is the task for this issue:

- upgrade sweetalert from sweetalert 1.x to sweetalert 2.x. 

The relevant code is in https://github.com/codebuddies/codebuddies/blob/38543a844f06d50466ee0eec7596e81c18fb13ab/client/layouts/layout.js. As Connie mentioned above, sweetalert 1.x currently only supports one confirm button. But if we upgrade all the sweetalerts to 2.x, we'd be able to support something like this: 
![image](https://user-images.githubusercontent.com/4512699/46913775-89207200-cf48-11e8-99c9-ad05db65f5cf.png)

I will file a separate bug so that the Github title reflects this task. Thanks! And sorry for the slow reply.

**Comment by lpatmo** [comment]
See: https://github.com/codebuddies/codebuddies/issues/1057
