### ISSUE TITLE
CSS: Prevent long URLs from overflowing content box on profile page, in the list of completed hangouts

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#823]
The problem:
![screen shot 2018-04-15 at 11 40 48 pm](https://user-images.githubusercontent.com/4512699/38793571-b22a62c6-4106-11e8-8109-3fd56540445a.jpg)

The solution:
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

Note:
@railsstudent solved a similar issue in https://github.com/codebuddies/codebuddies/pull/804/files.

Probable place to fix:
p.overflowtext in `client/css/_hangout_card.scss`

This is a `good-for-beginners` issue. Docs are at docs.codebuddies.org. Let us know if you want to work on it, and if you need help!

**Comment by dantesolis** [comment]
hey guys, back from sick leave. can I tackle this one? if it's not yet taken? 

DS

**Comment by dantesolis** [comment]
@nalbina. I'll take it. Thanks  :)

**Comment by railsstudent** [comment]
@dantesolis  Can you finish other issues under your username too? thanks.

**Comment by dantesolis** [comment]
@railsstudent will do, let me see which other are on my name. Thanks ;)

**Comment by lpatmo** [comment]
Closing this issue, since https://github.com/codebuddies/codebuddies/pull/839 applies `overflow-wrap: break-word;` globally to `p` tags. So the problem on the profile page was fixed.

**Comment by lpatmo** [comment]
@dantesolis I believe the three issues assigned under you are https://github.com/codebuddies/codebuddies/issues?q=dantesolis+is%3Aopen. If you don't want to work on them anymore, or if you have any questions, let us know! :)

**Comment by dantesolis** [comment]
@lpatmo still want to work on them :) :) was looking for my issues. Thanks 👍
