### ISSUE TITLE
Vote: Change "Hangouts" to say "Calendar" on the nav?

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#828]
We generally want to point users to the "hangouts" tab (codebuddies.org/hangouts), where they can RSVP for hangouts on the calendar and schedule new ones. And a leaderboard/global activity feed will soon be on the sidebar on this page too.

I've been thinking that "calendar" is a more useful term than "hangouts", like so:

![screen shot 2018-04-16 at 8 48 56 pm](https://user-images.githubusercontent.com/4512699/38847676-be31655e-41b7-11e8-8ef3-2d3a5cbbeca9.jpg)

If you like this idea, please vote with a "thumbsup" emoji. If you're against the idea, please leave a comment to downvote the idea.

**Comment by railsstudent** [comment]
I prefer Hangouts over Calendar.

**Comment by nalbina** [comment]
Voting for Hangouts here. One of the compelling points of codebuddies are the hangouts, so that should atleast be visible in the menu at all times.

**Comment by lpatmo** [comment]
@railsstudent @nalbina Thank you for voting/leaving a comment! It seems others don't have a strong opinion, so I will close this issue.
