### ISSUE TITLE
CSS: prevent overflow of long URLs on discussion threads

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#837]
The problem:
![screen shot 2018-04-19 at 12 29 15 am](https://user-images.githubusercontent.com/4512699/38977297-d6e6fda4-4368-11e8-966c-f62e4c6ac8eb.jpg)

The solution:
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

Note:
@railsstudent solved a similar issue in https://github.com/codebuddies/codebuddies/pull/804/files.

This is a `good-for-beginners` issue. Docs are at docs.codebuddies.org. Let us know if you want to work on it, and if you need help!

**Comment by saminap92** [comment]
I can look at this if it is not taken up by anyone else already

**Comment by railsstudent** [comment]
Go for it

**Comment by piyushmittal25** [comment]
Actually I already send a pull request for that

**Comment by nalbina** [comment]
closed via f6846a8. thanks again @piyushmittal25
