### ISSUE TITLE
IDEA: Incorporate "buy me a coffee" links onto user profiles on CodeBuddies

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#844]
@distalx raised this idea. 

https://www.buymeacoffee.com/ is a platform that launched late 2017 that lets users easily create a "buy me a coffee" donate page for themselves, which I just found out about today (thanks @distalx). 

On CodeBuddies, we've been discussing various ideas to support and encourage more hangout organizers -- including the idea of reimbursing each hangout organizer $5 (with a limit of 5 total reimbursements) on our Open Collective at codebuddies.org/opencollective, if they can submit a screenshot showing that at least one other person joined *and* that learnings were shared on the hangout page. We're also working on gamifying the app (#829) to applaud active organizers with points on a leaderboard.

What if -- instead of doing a lot of vetting work on our side -- we let hangout organizers save a buymeacoffee ID on their CB profile page, and automatically display a coffee icon next to their usernames on the leaderboard, and next to their names on a hangout event page? That way users/participants could tip someone directly if they've benefited from some hangouts an organizer has started.

And the CB sponsorship team could also contact potential sponsors to "sponsor a hangout" -- e.g. $250 will sponsor 50 hangouts. That way, instead of each organizer applying for a reimbursement directly, an admin on CB's side could tip trusted organizers on their buymeacoffee profiles (sidestepping anyone who's been trying to game the system), and then apply for a bulk reimbursmeent on opencollective.com/codebuddies.

**Comment by rmorabia** [comment]
I'm on board with the idea of adding the option for tipping next to a CB user's profile so someone can tip if they find a Hangout useful.

However -- Is there an alternative platform like BuyMeACoffee that works for both charity & individual tipping? Or does BuyMeACoffee support that themselves? I know if I was to do a Hangout (sooooooon), I'd want my tipping link to just link directly to a charity of my choice the way Amazon Smile does it.

**Comment by lpatmo** [comment]
On CB's side, we can have the options on a profile page be:

[link to your buymeacoffee profile page]
OR
[link to a charity of your choice]

How does that sound? That way the we can decide what we want our tips to go to. Only downside of linking to a charity of choice vs. buymeacoffee is I don't know what charity sites out there will display the total $ of donations collected. Because that number would be nice to see.

**Comment by rmorabia** [comment]
Yeah, it's definitely in the minority. It's only for big charities like Charity Water where you can create a custom fundraising campaign. Even something like OpenCollective -- if someone chooses to link to a project like that wouldn't necessarily show anything special & individual based on the referrer. But oh well, not a _huge_ deal.

**Comment by lpatmo** [comment]
My only fear is that the incentive of "coffee" might make beginner coders less likely to schedule hangouts out of the misguided notion that they have to be super prepared and also be prepared to "teach" whatever topic they proposed, when in reality the hangout organizer doesn't necessarily have to be prepared -- e.g. the hangout proposal could be "let's take turns reading this chapter out loud to each other and discussing" to "I want a silent hangout to work on some javascript while other people are working on javascript too." 

On the other hand, maybe I'm overthinking this and it'll be all right. I am looking forward to seeing the reactions to this feature after it's deployed. Will people buy each other coffee? dundundun

PS I will reach out to buymeacoffee to see if they want to sponsor some hangouts.

**Comment by lpatmo** [comment]
Update: I've reached out to Buy Me A Coffee about them potentially giving CB members some credits in return for us listing them as a sponsor, and they told me they would get back to me! But they were busy with a Product Hunt launch, so I need to follow up with them. 

Let's add three additional profile fields:
1) Buy Me A Coffee link
2) Patreon link
3) Link to a non-profit a user might want to support

On a hangout page, above the description area, we could say something like:
"Did you learn a lot in this hangout? You can show the hangout organizer your appreciation by buying them a coffee!" [Buy Me A Coffee logo] [Patreon link if there is one] [Link to a non-profit the user supports]
