### ISSUE TITLE
Encourage using `git cz` (commitizen) by telling contributors about it in docs.codebuddies.org

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#850]
The staging branch now supports commitizen: http://commitizen.github.io/cz-cli/

This means that after `git add`, instead of `git commit`, I can type `git cz` and be walked through some prompts that'll package a better looking commit message.

Proposal:
1) Update docs.codebuddies.org (github.com/codebuddiesdotorg/documentation) to encourage users to use `git cz`
2) Make an announcement about it in the #cb-code channel on Slack

We obviously won't reject PRs if they don't follow cz, but `git cz` can help improve the quality of our commit messages.

**Comment by TomerPacific** [comment]
@lpatmo ,
is this issue still relevant? I am willing to take this one.

**Comment by TomerPacific** [comment]
@lpatmo ,
no problem. 
Just to make sure, I am going to edit the contributing.md file with the necessary information (found in the welcome directory).

**Comment by TomerPacific** [comment]
Created a [PR](https://github.com/codebuddies/documentation/pull/25)

**Comment by TomerPacific** [comment]
@lpatmo ,
consider closing this issue.
