### ISSUE TITLE
CSS Issues in profile completed hangouts column

### ISSUE THREAD

**Issue by stain88** [codebuddies/codebuddies#851]
Do you want to request a feature or report a bug?
**Bug**

What is the current behavior?
![label nowrap](https://user-images.githubusercontent.com/8461452/39297806-641fc646-493c-11e8-949e-7765e2b294d8.png)
![rsvp button](https://user-images.githubusercontent.com/8461452/39297807-64352bc6-493c-11e8-990b-541e017b00b8.png)

Both .label and .btn have a `white-space: nowrap;` property, from the default bootstrap styles.

What is the expected behavior?
Line breaks should be allowed, so that buttons and labels sit more nicely in the column.

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)
Chrome, Firefox, Safari, Edge

**Comment by aimeerpierce** [comment]
I'm looking for a beginner-friendly bug to tackle as a first-time contributor! I'd love to look into this one.

**Comment by railsstudent** [comment]
@aimeerpierce  Go for it. It is your.

**Comment by lpatmo** [comment]
@aimeerpierce Let us know if you need help getting started! Or if you're stuck on something. Feel free to ask in the #cb-code channel on the CodeBuddies Slack too.
