### ISSUE TITLE
EXPERIMENTAL IDEA: Global Silent Hangout Page (e.g. codebuddies.org/silenthangout)

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#852]
### Problem: 
Occasionally I'll have anywhere between 30 minutes and 3 hours some random evening or weekend where I want to be productive with my coding projects/learning goals, but I'll be too easily distracted to focus. 

In the past, I've found that having some study company (other people in a hangout at the same time, screensharing what they're working on if they want to, and sharing their productivity goals) has tended to make me feel less lonely, less distracted by random social media, and also a LOT more productive.

In the past, I would have two options:
- I can schedule a "silent hangout" on the site. WHAT STOPS ME: My fear in scheduling spontaneous hangouts is that no one would be around and would want to RSVP to it. Plus, thinking of a title and a description for the hangout takes effort. 
- Alternatively, I can ask in #general on the CodeBuddies Slack if anyone is up for a silent (study/coworking) hangout and share a meet.jit.si link. WHAT STOPS ME: typing "anyone around?" in a chatroom takes effort too, and I also don't want to be the only person who continues to have to explain the norms of a "silent hangout" on Slack every time. The norms, by the way, are:

```
1) Turn video and microphone off when you join the hangout
2) Share your goal for the time period you're here (basically, what you're working on) in the chat
3) Screenshare (optionally) if you can, even if you're just watching a video, because it's fun to see that other people are being productive! And if you're screensharing, you're less likely to tab to social media.
4) If another person joins and happens to be working on similar goals, and if you decide to pair up or talk/study together with that person, one of you can start a separate spontaneous hangout where you can dive deeper into that specific topic (and chat out loud using mic) without having to fear no RSVPs.
```

## Proposed experimental solution: 

1) Create a codebuddies.org/silenthangout page. Other URL name ideas welcome.
2) When a user goes to the page, they'll immediately see a popup showing the four "norms" above (in more concise text), and click on a button showing the words "Agree & Continue"
3) Once the popup disappears, on the page itself, the user will see:
- A Jitsi hangout loading 
- The norms below the hangout, encouraging the user to share their learning goal, including a button to start a spontaneous hangout if they've connected with someone interested via the chat
- A `learnings` section where they can share something they learned/accomplished. This feed will show 15 learnings/accomplishments at a time, and will be the same global learnings feed from the `learnings` collection found already on the CodeBuddies site. 

Proposal: In order to share a learning or to start a spontaneous hangout, the user will need to be logged in via Slack or Github. But in order to join the Jitsi hangout itself, they don't necessarily need have to have an account.

What do folks think about this idea? Would you participate in something like this to manage your own productivity?

I realize that we have similar 24/7 rooms within each study group already, but this idea is more global, the purpose of the silent hangout (it being a space for silent motivation/remote coworking) would be clearer, and the URL (codebuddies.org/silenthangout or codebuddies.org/coworking -- any votes??) would be more shareable too.

Note: We could also consider having this feature be a part of codebuddies.org/hangouts itself. Or at least, we should link to this page on the sidebar.

**Comment by stain88** [comment]
Aren't there already generic 24/7 co-working hangouts? thinking of #co-working1 channel here, but not sure how it got set up. The idea of an "obvious url" is a plus though.

**Comment by distalx** [comment]
I vote for codebuddies.org/anythinggoes

-----Original Message-----

**Comment by lpatmo** [comment]
> Aren't there already generic 24/7 co-working hangouts? thinking of #co-working1 channel here, but not sure how it got set up. The idea of an "obvious url" is a plus though.

Yep, but those 24/7 tabs aren't very shareable, and I'd like to see if we can make this 24/7 silent hangout a "norm" in the community, just as plusplus is a norm. I mean -- not everyone has to try it out if the idea doesn't appeal to them, of course -- but I am itching for this type of motivation, and it'd be wonderful if I could do less work to get the experience of a silent "yay, the fact that I see other people are working hard too" hangout every time I want it.

**Comment by lpatmo** [comment]
I made a prototype. Feedback welcome! Screenshots below.

Not logged in:
![screen shot 2018-05-04 at 6 38 06 pm](https://user-images.githubusercontent.com/4512699/39656104-9fa5cbbc-4fcb-11e8-80c6-a3be81463d28.jpg)

After a user has logged in:
![screen shot 2018-05-04 at 6 44 18 pm](https://user-images.githubusercontent.com/4512699/39656083-878b7f18-4fcb-11e8-9082-c36118950215.jpg)

After a user has joined the silent hangout:
![screen shot 2018-05-04 at 6 44 57 pm](https://user-images.githubusercontent.com/4512699/39656084-87a3931e-4fcb-11e8-994b-646aabefd57b.jpg)

**Comment by lpatmo** [comment]
@railsstudent I also tweaked the twitter warning functionality so that by default the checkbox is *unchecked*, and the message says "Tweet this message automatically out on @codebuddiesmeet."

**Comment by billglover** [comment]
Has this been implemented now? I'd always assumed this was the 24x7 space for silent productivity.

**Comment by lpatmo** [comment]
Yes, oops. Thanks. Let me close this issue. The implementation is at codebuddies.org/coworking.
