### ISSUE TITLE
Link directly to Slack invite page under "Start learning with us now!" heading on home page

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#861]
Problem:
On the home page of codebuddies.org, clicking on the second "get my Slack invite" button at the bottom of the page leads to the email input box opening up at the top.

Instead of using `<script async defer src="https://codebuddiesmeet.herokuapp.com/slackin.js?large"></script>`, let's simply link to http://codebuddiesmeet.herokuapp.com with the text _Get your Slack invite here._

Thanks to @sergeant-q for finding this bug, and @wuworkshop and @billglover for verifying.

Relevant file: `client/templates/home/home_logged_out.html`
```
205-  <div class="section home-ask">
206-    <div class="container">
207-      <div class="row">
208-        <div class="col-md-12">
209-          <h2>Start learning with us now!</h2>
210-          <div class="join-slack">
211:            <div class="slack-invite">
212-              <script async defer src="https://codebuddiesmeet.herokuapp.com/slackin.js?large"></script>
213-            </div>
214-            <p>Sign in with <a href="#" class="signIn link">Slack</a> or <a href="#" class="signInGithub link">Github</a>.
215-            <br />Select <strong>CodeBuddies</strong> or sign into the <strong>codebuddies</strong>.slack.com team.</p>
216-          </div>
217-        </div>
218-      </div>
219-    </div>
220-  </div>
```

**Comment by BogDAAAMN** [comment]
I'd love to claim this issue for my first time contribution!

**Comment by sergeant-q** [comment]
@BogDAAAMN it's all yours! 👍
