### ISSUE TITLE
Archive studygroups and discussions on `delete my account`.

### ISSUE THREAD

**Issue by distalx** [codebuddies/codebuddies#868]
r/n when user deletes their account we are archiving their [Hangouts](https://github.com/codebuddies/codebuddies/blob/3335e76cbbc325175abdd68f97e09d23399b412a/server/archived_users/methods.js#L49), [Learnings](https://github.com/codebuddies/codebuddies/blob/3335e76cbbc325175abdd68f97e09d23399b412a/server/archived_users/methods.js#L50) and other informations related to that user.

Similarly archive their Discussions and StudyGroups.

**Comment by nodeiris** [comment]
Can't delete my account. No matter how many times I click "Delete".

**Comment by distalx** [comment]
> Can't delete my account. No matter how many times I click "Delete".

Not able to reproduce this.

**Comment by lpatmo** [comment]
@ghost I was able to delete my account successfully too. Can you give us more details, like which browser you were using? And do you see any errors in the console when you click to delete?
