### ISSUE TITLE
Feature Reqest: Mass-notify Study Groups & Hangout RSVPers

### ISSUE THREAD

**Issue by rmorabia** [codebuddies/codebuddies#871]
Do you want to request a feature or report a bug?

Feature request

What is the current behavior?

If there are any non-cancellation changes to the Hangout (eg. changing the date), those who RSVP get zero notification.

What is the expected behavior?

Either be able to send a custom notification to the relevant users on Slack or via email, or automatically have the CodeBuddies bot say "Hey, changes have been made!"

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)

All.

**Comment by billglover** [comment]
Remember GDPR: we’ll now need to
- gather email :frowning:
- ask people for permission to email them
- handle cases where people don’t want to provide email

I’ve personally really enjoyed the email free CodeBuddies experience so far.

**Comment by railsstudent** [comment]
@rmorabia   It is an excellent suggestion, no fun to miss a hangout due to time change.  
I think to reuse the slack notification logic in create hangout.
When hangout is updated, send notification to announcement and designated study group slack channels.
