### ISSUE TITLE
Unit test and continuous integration.

### ISSUE THREAD

**Issue by distalx** [codebuddies/codebuddies#89]
Meteor 1.3 officially supports the mocha framework. We should take an advantage of it and add unit test to cb.
And also we should start using continuous integration.

**Comment by foxiae** [comment]
Oh! Something kinda related? https://www.codacy.com/ is an automated code review site that's free for open source projects. It may be good to have with integration testing and such.

**Comment by camilleriluke** [comment]
First set of unit tests: https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/280 `\0/`

**Comment by lpatmo** [comment]
Note: started a new branch for unit tests in `issue-89-tests`.

**Comment by osanseviero** [comment]
I'll drop some resources here if you want to check them

- http://xolv.io/blog-posts/2013/04/end-to-end-testing-for-web-apps-meteor
- https://github.com/xolvio/chimp

**Comment by osanseviero** [comment]
Revisiting this topic, I'll probably jump into this in the following weeks.

**Comment by osanseviero** [comment]
Revisiting this topic, I'll probably jump into this in the following weeks.

https://guide.meteor.com/v1.3/testing.html

Checking that guide, I think that we could have
- Unit tests
- Integration tests
- e2e tests

The hard part is that pretty much all of the user stuff is related to Slack, so we will need to see how to mock that for integration and e2e tests. Meteor seems to have nice support for testing templates, so I don't expect that part to be too much work (except Slack).

Before starting to work in this, we should probably define what we want to test and how we want users to interact with them (I saw that there are some services that allow to run tests for each PR, but for now I guess that [this](https://guide.meteor.com/v1.3/testing.html#command-line) is enough).   

Also, if we don't want to go with Meteor standard testing, creating a tests directory and having our tests there should work. I think that Meteor tools/libraries should work for us.

What do you think?

**Comment by nalbina** [comment]
@distalx *poke*

**Comment by billglover** [comment]
I'm closing this because work on it has started and it isn't clear that this issue can ever complete. If we want to track the implementation of specific unit tests, we can raise issues covering specific areas of coverage we'd like to add. When doing so, feel free to reference #89.
