### ISSUE TITLE
"Click to load the hangout" button throws an error

### ISSUE THREAD

**Issue by wuworkshop** [codebuddies/codebuddies#898]
Do you want to request a feature or report a bug?
Bug on the newly released coworking page here:
https://codebuddies.org/coworking

What is the current behavior?
When you click the "Click to load the hangout" button you get an error in DevTools that says:
`Uncaught TypeError: Cannot read property 'username' of null`

What is the expected behavior?
Clicking it should load the hangout.

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)
Saw this is the latest version of desktop Firefox and Chrome on my MacBook.

**Comment by lpatmo** [comment]
Thanks for reporting, @wuworkshop, and thanks @distalx for fixing! I've hotfixed this.
