### ISSUE TITLE
Upgrading to FontAwesome v5 from v4

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#907]
Let's explore how (or if we can easily) upgrade to FontAwesome v5, which gives us more icons like a `Patreon` icon.

**Comment by distalx** [comment]
This might help.

https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by lpatmo** [comment]
Does https://github.com/codebuddies/codebuddies/pull/908/files complete our upgrade, or do we need to update all our old fontawesome names as well?

**Comment by distalx** [comment]
Yes, we do have to update the prefixes of old icons according to this guide `https://fontawesome.com/how-to-use/upgrading-from-4`
