### ISSUE TITLE
Feature: a dedicated channel for promotional posts

### ISSUE THREAD

**Issue by billglover** [codebuddies/codebuddies#909]
**Do you want to request a feature or report a bug?** feature

**What is the current behavior?** Members of the community are unsure where (or even if) they should post promotional material. Topic focussed channels may seem like an obvious choice but in some cases these are low traffic and so people gravitate to posting in general channels. Even though intentions are good, this can be seen as spammy.

**What is the expected behavior?** Members should have confidence about where they can go to promote material, events, or other work they are involved in. General channels are free from links or promotional style posts that could be seen as spammy.

**Comment by kvie** [comment]
I am all for a promotional channel. I'm personally interested in what other people are working on to contribute to the coding and creation community overall and I want to support members of the community the same way that members support the community. Being able to share their projects with confidence might lessen the burden on members and the community both.

**Comment by angelocordon** [comment]
What about other kinds of links that could potentially belong to multiple channels? Does it make more sense to post in `#general` than to x-post in multiple channels?

**Comment by billglover** [comment]
We have `#brag` which appears to be low volume. I wonder if this could be re-named to  `#promote`? I brag about my personal projects in  `#personal-projects`.

**Comment by lpatmo** [comment]
I like the idea of renaming #brag to #promote! I've always thought of suggest #personal-projects as a place to promote, too, but this makes it a lot clearer. Especially if a post is asking for users to sign up for a different service.
