### ISSUE TITLE
Feature: make it easier for people to host hangouts on alternate platforms

### ISSUE THREAD

**Issue by billglover** [codebuddies/codebuddies#910]
**Do you want to request a feature or report a bug?** feature

**What is the current behavior?** Some members of the community have existing channels for running hangouts (Twitch, Google Hangouts, Skype, etc.). Although members can leave a comment that indicates the hangout is hosted elsewhere, this can easily be missed and so hosts feel the need to share direct links on Slack. This can be interpreted as spammy.

**What is the expected behavior?** Given that we have stated that it is acceptable for hosts to use alternate platforms to host hangouts, we should consider making this prominent in the existing hangout announcements. This will discourage hosts from posting direct links on Slack channels.

**Comment by sergeant-q** [comment]
@billglover can you give me an example of what you're looking for? Is the feature request simply to add more details in the Slack hangout notification with the url or the alternate platform or?

**Comment by lpatmo** [comment]
Here's an idea of how we could implement this feature:

![screen shot 2018-06-16 at 12 04 59 pm](https://user-images.githubusercontent.com/4512699/41501670-a19b00d2-715d-11e8-95ed-836bddcdd112.jpg)

- Scheduler of the hangout can check this checkbox if they want to use an alternative platform
- If checkbox is checked, they'll see a field where they can input a URL (e.g. a zoom URL or a google hangouts URL) on participants should click on
- If checkbox is checked and value is filled out, Jitsi iframe disappears and useres sees a link to the google hangout or the Zoom conference, etc.
- Embedding a Twitch livestream (https://dev.twitch.tv/docs/embed/everything/) might take more than a link; I'll have to take a closer look at the docs.

**Comment by sergeant-q** [comment]
@lpatmo will this setting be available after the hangout has been scheduled or before?

I like the idea but trying to figure out how this will be passed down in the Slack notification.

**Comment by lpatmo** [comment]
I was thinking a host would be able to change the setting after they schedule a hangout, since they might not have the link ready at the time the create hangout popup is open.

**Comment by lpatmo** [comment]
`"edit a hangout and resend the notification"` is done for updated hangout times. @railsstudent added that feature in the last release. I'm not convinced we need to make Slack send a new notification if the hangout platform is updated, though, because in the past we never put the hangout link directly in the Slack notification either. People simply clicked through to the hangout page and joined the hangout from there.

Only difference now is that people would be clicking on a Zoom, Twitch, or Google Hangout link instead of a Jitsi link.

**Comment by billglover** [comment]
I had originally assumed that people would be able to specify the link during hangout creation/editing on this screen.

<img width="828" alt="screen shot 2018-06-17 at 22 38 03" src="https://user-images.githubusercontent.com/94501/41512377-76ec512e-727f-11e8-9717-27a76cfc9f44.png">

I haven't used any of the other platforms though so it may well be the case that users aren't given a link until the point at which the hangout starts. At that point it's a bit late to me modifying the hangout properties.

**Comment by lpatmo** [comment]
Note to self: prioritize this issue, since @julianjohannesen and co. would find it beneficial to be able to insert a link on Hangout Create pointing directly to Zoom, instead of having to paste it into the description.
