### ISSUE TITLE
Feature: add channel guidance to the welcome/reminder bot

### ISSUE THREAD

**Issue by billglover** [codebuddies/codebuddies#911]
**Do you want to request a feature or report a bug?** feature

**What is the current behavior?** New members (and even some of us who have been around for a while) need some guidance as to the purpose of the more general channels. When posting a message that doesn't relate to a specific topic it can be unclear which of these general channels should be used (e.g. `#general` vs `#water-cooler` vs `#announcements`). When a message doesn't match the expectations of channel members this can be interpreted as spammy behaviour.

**What is the expected behavior?** Can we consider adding a message to the welcome bot that gives a polite but impersonal guidance as to the purpose of the more general channels. The aim would be to allow the bot to be triggered to provide guidance and avoid conflict between channel members. The language used should assume that everyone is well-intentioned and offer guidance rather than be an automated way to call people out for breaking the rules.

**Comment by billglover** [comment]
Continued discussion on Slack suggests that guidance could be considered around:
* guidance around where to post general messages/announcements
* guidance around what is considered acceptable to post
* guidance around things you may want to re-consider before posting

**Comment by spirodonfl** [comment]
Perhaps we can add some verbiage around users not joining just for posting links to their community solely and making sure they contribute back directly? Some kind of encouragement, too, like "If you're an active contributor to the cb community you're more likely to get awareness and build trust" or something along those lines.

**Comment by lpatmo** [comment]
I remember that we added something to https://github.com/codebuddies/greetbot; if we want to tweak the message there further, let's file an issue on that repo!
