### ISSUE TITLE
Unable to login via Github or Slack

### ISSUE THREAD

**Issue by buoyantair** [codebuddies/codebuddies#912]
### Do you want to request a feature or report a bug?
Report a bug
### What is the current behavior?
I am not able to login to codebuddies.org via Github or Slack

After I log into slack or github and give authorization to login, I get a blank window and I am not redirected to codebuddies as should have been if I logged in successfully.

### What is the expected behavior?

I should be able to login via github or slack and when I authorize codebuddie's application to use my user data on those platforms, I should be logged in and redirected to codebuddies.org

### Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)

This problem is seen on both Chromium and Firefox
Chromium (Version 67.0.3396.79 (Official Build) Arch Linux (64-bit))
![image](https://user-images.githubusercontent.com/5159834/41458063-318db66e-70a3-11e8-85b8-b3b8188f66e3.png)

Firefox 60.0.2 (64-bit)
![image](https://user-images.githubusercontent.com/5159834/41458221-99096d88-70a3-11e8-941f-9a7ba4265614.png)

**Comment by distalx** [comment]
@buoyantair Thanks a lot for filing this issue! 
I was able to login to my account successfully.
do you see any errors in the console when you try to login?

**Comment by buoyantair** [comment]
@distalx I am not sure because I tried it again yesterday after a couple of hours, and it turns out I was able to login! :O

**Comment by distalx** [comment]
Please re-open this issue if it still occurs.
