### ISSUE TITLE
Add link to forum.codebuddies.org in the navbar under *Community*

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#919]
Instructions:
Add a link to https://forum.codebuddies.org in the navbar under the "Community" section, under the "Slack" link and above the "Github" link:

![image](https://user-images.githubusercontent.com/4512699/43043169-c8950052-8d41-11e8-813c-9ac902438fc6.png)

+++++
Instructions for new contributors:
1. Read http://docs.codebuddies.org to set up meteor and get the app running!
2. Fork the project, create a new branch, commit the fix, and submit a PR.
3. If you have questions, leave a comment here or ask in the #cb-code channel on Slack.

If you want to work on this issue, please leave a comment to claim it before you submit a PR.

**Comment by praveeno** [comment]
hey, i can help you with this

**Comment by railsstudent** [comment]
@praveeno  It is all yours.  Can you wait until I finish upgrading fontawesome icons of the site to v5.
#907 is currently WIP.

**Comment by railsstudent** [comment]
Can show https://fontawesome.com/icons/comments?style=solid  icon in menu

**Comment by praveeno** [comment]
Sure @railsstudent

**Comment by kelikaterina** [comment]
Hello!
I'm beginner and the first time here.  
I believe I will manage this task. Or everything is already done?

**Comment by stain88** [comment]
Looks like it's already claimed by @praveeno, @kelikaterina. Just holding for @railsstudent to finish a PR first

**Comment by lpatmo** [comment]
@praveeno The fontawesome PR has been merged in, so you can tackle this issue now. :) Sorry for the wait. 

For future icons, we are using this syntax:

<i class="fas fa-NAME"></i>

Please do not use `far` or `fal` (PRO icons that need a license), only `fas` or `fab`.  

Thanks! (And let us know if you're still interested in working on it.)
