### ISSUE TITLE
Define a Content Security Policy

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#921]
h/t @oliikit for the flag.

```
Alternatively, the <meta> element can be used to configure a policy, for example: <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src https://*; child-src 'none';">
```

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by distalx** [comment]
@lpatmo I believe we are already managing CSP for CB using [browser-policy](https://atmospherejs.com/meteor/browser-policy) package.

**Comment by lpatmo** [comment]
Thanks @distalx! I will close this.
