### ISSUE TITLE
Fix Hangouts link in README.md

### ISSUE THREAD

**Issue by praveeno** [codebuddies/codebuddies#927]
Do you want to request a feature or report a bug? Bug
Readme.md file points to old hangouts subdomain - http://hangouts.codebuddies.org/

What is the current behavior?
![image](https://user-images.githubusercontent.com/19618730/43366260-6b3245ba-9358-11e8-9f71-14e53f2c24cd.png)

What is the expected behavior?
Hangouts link should point to this URL - https://codebuddies.org/hangouts

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)
All

**Comment by wuworkshop** [comment]
@praveeno Out of curiosity, where did you find that link?

**Comment by praveeno** [comment]
in README File

**Comment by praveeno** [comment]
hey @wuworkshop , should we remove this link ?

**Comment by wuworkshop** [comment]
@praveeno Instead of removing the link in the README, it should be updated to the correct URL. The URL should be this: https://codebuddies.org/hangouts

**Comment by peoray** [comment]
I would like to pick up this issue if nobody has indicated any interest yet!

**Comment by railsstudent** [comment]
@peoray  It is yours.
