### ISSUE TITLE
Some users unable to log in, with "blocked frame" error in the console

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#934]
See screenshots:
![image](https://user-images.githubusercontent.com/4512699/43815871-b7bdfaa2-9a86-11e8-86c5-b6ef789ff7b0.png)

![image](https://user-images.githubusercontent.com/4512699/43815862-a36482b0-9a86-11e8-9d26-7d3a275b0038.png)

**Comment by lpatmo** [comment]
Also: ![image](https://user-images.githubusercontent.com/4512699/43815927-0b88c3ce-9a87-11e8-8b3d-fd8d8cf783ca.png)

I googled the "blocked a frame with origin" error message and found this: 
https://stackoverflow.com/questions/44530467/meteor-single-signon-oauth-popup-is-blank-cross-origin-frame-error

**Comment by lpatmo** [comment]
Update:
Logging in on https://www.codebuddies.org will not work.
Logging in on https://codebuddies.org is fine.

I added a redirect on DigitalOcean to hopefully get www.codebuddies.org redirecting to codebuddies.org, but it may be a few hours before it works.

Not sure if there's a best practice way to redirect www -> https://. 

The meteor forums at https://forums.meteor.com/t/solved-single-signon-oauth-blank-popup-cross-origin-frame-error/37237/6 suggest doing this:
```
//[project]/imports/startup/client/force_www_redirect.js
import { Meteor } from 'meteor/meteor'

Meteor.startup(function () {
    if (location.host.indexOf('https://codebuddies.org') !== 0) {
        location = 'https://codebuddies.org'
    }
})
```
Thoughts?

**Comment by distalx** [comment]
@lpatmo Great work on hunting this down. The above mention solution should work.
