### ISSUE TITLE
Schedule a hangout from Slack directly

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#937]
Idea proposed by @gauravchl: `#create-silent-hangout topic: learn graphql with me. Time: tomorrow at 7pm`. Message could create a new hangout on codebuddies.org.

@stain88: `POST codebuddies.org/hangouts?type=silent&title=work%20on%20greetbot&time=1900&date=20180812&timezone=UTC&organiser=stain88`

@angelocordon: Could be set up as `/hangout [type] [title] [time] [timezone]`

**Comment by d3vild06** [comment]
Some things to consider and discuss:

*Authentication/Authorization*
Today we require a user to be logged in to create a new hangout. Primarily to protect from anyone creating and deleting a hangout in the site/app. We also capture who the organizer is and this info is also fed into their profile (# of hangouts created for example). 

*Unique identifier for a user*

With the recent github login feature we added, users can login with either Slack or GH. We now could possibly have two distinct users in the system. 

We can't be certain our users use the same email across both accounts. We need to figure out how to deal with multiple accounts and tying them to one user. 

Lastly, currently we are not exposing any REST API for CB. This would be something new we would need to add to the site. That in itself requires a ton of architectural decisions regarding the CB site

**Comment by stain88** [comment]
How does the login work? Does it just match up profiles based on email? Or filling in the GitHub field in your profile? Could we add a "slack username" field?

Having an API exposed would be a pretty cool feature: those could be hooked up to `greetbot` to get upcoming hangouts, create a new one, or view study groups / send invite to a study group

**Comment by railsstudent** [comment]
Claimed by @gauravchl

**Comment by gauravchl** [comment]
This is done!

**Comment by lpatmo** [comment]
For archival purposes, wanted to congratulate @gauravchl again on closing this issue (a couple of people have commented to me how impressive this PR was) and to drop a link to https://medium.com/codebuddies/interview-w-gaurav-coding-a-slack-integration-that-lets-users-schedule-codebuddies-hangouts-b8f8e43cedc6.
