### ISSUE TITLE
Feature request - reduce header height on study group page

### ISSUE THREAD

**Issue by julianjohannesen** [codebuddies/codebuddies#939]
## Current behavior:
The study group landing page has an enormous header dedicated to a description of what the page is and a button to create a study group. The search bar appears at the bottom of the page just above the fold on my laptop and you can't see any of the extant groups.

## Desired behavior:
Reduce header size dramatically and move "create a group" button to top or bottom right corner where one often sees some sort of +New button. This will bring the search bar to the top and show a sample of extant groups

## Affects:
Smaller screens

**Comment by railsstudent** [comment]
@julianjohannesen any screen capture.  I am using old mac book air 13" and do not observe the behavior. Thanks.

**Comment by lpatmo** [comment]
@phavor I believe @julianjohannesen is talking about this page: 

https://codebuddies.org/study-groups
![image](https://user-images.githubusercontent.com/4512699/46130044-26f80b00-c1ed-11e8-81e1-8703a8d6e0ad.png)

Hope this helps!

**Comment by 20djm** [comment]
Hi all I'm going to start working on this!
