### ISSUE TITLE
Default email notification settings

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#948]
- An easy way for study group owners to send out an announcement to the group right now is to start a new discussion within the study group
- Members will only get those notifications if they have setting checked in their Email Notification Settings
- Proposal: set the following as default:

![image](https://user-images.githubusercontent.com/4512699/44616139-4b805200-a7ff-11e8-856d-330634b29f4b.png)
- We need to make sure to add a link to this Settings page on the footer of each email notification, next to the "unsubscribe" link that's already there

**Comment by stain88** [comment]
`Unsubscribe` takes you to a page with a Yes/No option, for that specific email type.
I think @lpatmo wants another link, "Change your email preferences", which goes directly to the settings page.

**Comment by lpatmo** [comment]
@railsstudent The relevant email template to edit should be `private/templates/email/new_member.html`! 

As for testing, I _think_ if the settings-development.json SMTP API password key is updated, it will work, but I don't remember if there is another step. @distalx, do you happen to remember?

**Comment by distalx** [comment]
This emails are being triggerd via cron job. it can be found here
https://github.com/codebuddies/codebuddies/blob/38543a844f06d50466ee0eec7596e81c18fb13ab/server/cron_job/methods.js#L95

For testing keep `isModeDebug` : `true` and the cron will run at every 4 minutes.
https://github.com/codebuddies/codebuddies/blob/f8018a08e09de340c925d61c3a2b4292f9988f7b/settings-development.json#L3

**Comment by distalx** [comment]
@lpatmo 
>The link to the "settings" page is built up like this: `https://codebuddies.org/profile/{{USERNAME}}/{{USER_ID}}/account-settings`

The above mention solution will only work if the user has already signed in, otherwise, the app will redirect the user to the home page.

@railsstudent 
The current **unsubscribe** link takes the user to the "_unsubscribe me_" route. here, `unsubscribeLinkId` is unique for each user.
https://github.com/codebuddies/codebuddies/blob/f8018a08e09de340c925d61c3a2b4292f9988f7b/lib/routes.js#L300
This route renders the `unsubscribeFromMailingList` template. And the user can _confirm_ or _deny_ this changes.
https://github.com/codebuddies/codebuddies/blob/ae338f68b1a1b7ca61dea941777df380cce5d644/client/templates/settings/unsubscribe_from_mailing_list.html#L1

Instead of just providing confirm and deny option, lets fetch the email preference of that user by using `unsubscribeLinkId` and display it. And a user can update their preferences.

cc @stain88.

**Comment by railsstudent** [comment]
@distalx  I am working on unsubscribe link and CB Mailer returns error log
20181002-04:41:00.052(-4)? inside mailer new_hangout
I20181002-04:41:00.799(-4)? { Error: Invalid login: 535 5.7.8 Sorry.
I20181002-04:41:00.800(-4)?     at SMTPConnection._formatError (/Users/connieleung/.meteor/packages/email/.1.2.3.1d12ouy.i83b++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)
I20181002-04:41:00.801(-4)?     at SMTPConnection._actionAUTHComplete (/Users/connieleung/.meteor/packages/email/.1.2.3.1d12ouy.i83b++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:1254:34)
I20181002-04:41:00.802(-4)?     at SMTPConnection._responseActions.push.str (/Users/connieleung/.meteor/packages/email/.1.2.3.1d12ouy.i83b++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:341:26)
I20181002-04:41:00.802(-4)?     at SMTPConnection._processResponse (/Users/connieleung/.meteor/packages/email/.1.2.3.1d12ouy.i83b++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)
I20181002-04:41:00.803(-4)?     at SMTPConnection._onData (/Users/connieleung/.meteor/packages/email/.1.2.3.1d12ouy.i83b++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)
I20181002-04:41:00.803(-4)?     at TLSSocket._socket.on.chunk (/Users/connieleung/.meteor/packages/email/.1.2.3.1d12ouy.i83b++os+web.browser+web.cordova/npm/node_modules/node4mailer/lib/smtp-connection/index.js:658:51)
I20181002-04:41:00.803(-4)?     at emitOne (events.js:116:13)
I20181002-04:41:00.804(-4)?     at TLSSocket.emit (events.js:211:7)
I20181002-04:41:00.804(-4)?     at addChunk (_stream_readable.js:263:12)
I20181002-04:41:00.804(-4)?     at readableAddChunk (_stream_readable.js:250:11)
I20181002-04:41:00.805(-4)?     at TLSSocket.Readable.push (_stream_readable.js:208:10)
I20181002-04:41:00.805(-4)?     at TLSWrap.onread (net.js:597:20)
I20181002-04:41:00.805(-4)?   code: 'EAUTH',
I20181002-04:41:00.805(-4)?   response: '535 5.7.8 Sorry.',
I20181002-04:41:00.806(-4)?   responseCode: 535,
I20181002-04:41:00.806(-4)?   command: 'AUTH PLAIN' }
I20181002-04:42:00.008(-4) (percolate_synced-cron.js:95) SyncedCron: Starting "initial email".
I20181002-04:42:00.010(-4) (percolate_synced-cron.js:95) SyncedCron: Finished "initial email".
^[[1;2DI20181002-04:43:00.010(-4) (percolate_synced-cron.js:95) SyncedCron: Starting "initial email".
I20181002-04:43:00.013(-4) (percolate_synced-cron.js:95) SyncedCron: Finished "initial email".

How can I update smtp login? Thanks.

**Comment by railsstudent** [comment]
Found smtp config in settings-development.json.

**Comment by railsstudent** [comment]
Cc @lpatmo

**Comment by lpatmo** [comment]
Sorry for the slow reply! I don't really understand the error. My guess is the API key for `password` in settings-development.json key needs to be updated, so I created a new one in a new test Sparkpost account, but I haven't had any luck getting an email to fire. I think maybe I need to have the domain verified first. There is a Slack Sparkpost community that I joined (http://slack.sparkpost.com/) and I asked for some clarification in there.

**Comment by railsstudent** [comment]
Thanks Linda for the response. I am using a workaround to dump the unsubscribe link in console and paste it to browser to test at the current moment

**Comment by lpatmo** [comment]
Okay, I finally remembered how to get back into the old account that had the domain already verified, and I have a new key I will DM you on Slack.

**Comment by railsstudent** [comment]
@lpatmo I can receive email in my email account now. thanks
