### ISSUE TITLE
Unable to get slack invite

### ISSUE THREAD

**Issue by Danny-G-Smith** [codebuddies/codebuddies#959]
When I click on [slack invite](http://codebuddiesmeet.herokuapp.com/) I get the following error. 

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

This happens from multiple browsers and from multiple IP address.

**Comment by TheBaileyBrew** [comment]
Same here. It's an error across all browsers (Firefox, Safari, Chrome, Edge) from my end as well regardless of my network connection.

**Comment by billglover** [comment]
@Danny-G-Smith, @TheBaileyBrew if you'd like an invite to Slack feel free to get in touch while we investigate the issue with the auto-invite. Best to drop me a mail: bill@billglover.co.uk.

**Comment by billglover** [comment]
@distalx this feels like an app that sits idle for most of the time so shouldn't take much in the way of resource. Do we have data that shows how often it is being called (and how often the invites are successful)? I wonder if we need to consider:

* the need for auto-invite in the first place
* different hosting options

**Comment by lpatmo** [comment]
App is back up at https://codebuddiesmeet.herokuapp.com/. Had to merge in latest code to fix bug. Thanks for filing, @Danny-G-Smith!
