### ISSUE TITLE
Turn CB signup plugin on home page into an HTML link

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#962]
We had to merge in the latest code from rauchg/slackin repo, which has a bit of broken plugin. So it'll be easier to turn it into a link instead of using the iframe.

Should link to https://codebuddiesmeet.herokuapp.com.

Currently looks like:
![image](https://user-images.githubusercontent.com/4512699/45474311-4b80bd00-b6ee-11e8-9c7c-1c73aa275eef.png)

Turn into: 
![image](https://user-images.githubusercontent.com/4512699/45474547-ea0d1e00-b6ee-11e8-9801-c829b3ad4d0c.png)

Docs: docs.codebuddies.org

**Comment by drunkenkismet** [comment]
Currently working on this issue as part of a walkthrough series.

**Comment by lpatmo** [comment]
Thanks @drunkenkismet!
