### ISSUE TITLE
Star (or highlight) active groups on the /studygroups page

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#964]
Thanks to @clockwerkz for this idea:

Clicking through the groups, it's hard to figure out which ones are active unless you click through and look through progress logs or past hangouts. 

Would be helpful to highlight the active ones.

**Comment by lpatmo** [comment]
The specific page I'm talking about is this one:
![image](https://user-images.githubusercontent.com/4512699/46131189-e6e65780-c1ef-11e8-9d3f-22f7aa87655e.png)

As users scroll and join groups, it can be hard to tell which study groups are still active. 
(Note: in reality, most activity I've seen from study groups has moved to private channels or DMs on Slack. But let's assume that we want to figure out a way to encourage more usage of this feature.)

Steps for contributors:
1) Read https://docs.codebuddies.org to get set up
2) We have to decide how to define "activity." Last time any data associated with a study group was updated, maybe? If so, we'd need to create a new `updated_at` field for the `Study Groups` collection, and update it with a timestamp whenever new data is saved into a particular study group's document.
3) Maybe we could put a "Last activity: [timestamp]" text on the card for the study group itself.

Thoughts/other ideas welcome on the proposal above.

**Comment by mahamshahid18** [comment]
Hi @lpatmo I'd like to work on this issue.

I like your suggestions. Other things that can be done are:
* Add a `Created On` field to the db and also add it on the card
* As a further addition to this, maybe as an extension for the future, the cards can be filtered by their `created on` date or by latest activity (as you mentioned above)

**Comment by mahamshahid18** [comment]
This is great, this really helps. I'll start on this in a bit ^_^

**Comment by lpatmo** [comment]
Note: we may have to double check that `createdAt` is actually being saved every time a new study group is created. @mahamshahid18 I'm also happy to file this as a separate Github issue in case it is a real bug, and you can continue working on this bug after that issue is fixed.

**Comment by mahamshahid18** [comment]
I'll take a look at this and confirm if it is indeed a bug. I'm working on the hangouts card issue right now. I'll start this one afterwards 👍

**Comment by mahamshahid18** [comment]
@lpatmo just checked, the `createdAt` field is being saved, so we don't need to worry about that 😅

**Comment by mahamshahid18** [comment]
Hey @lpatmo I've added the logic to update the value of the `updatedAt`  field when a study group document is modified. This is working (it's getting updated).
However, I've run into a weird problem. The `updatedAt` field is not saved when a new study group is created. Using ctrl+m on the main study groups page, I can see that none of the new groups that I created had an `updatedAt` field, but if I navigated inside a specific study group page, then the `updatedAt` field does appear.

Does this make sense?

**Comment by lpatmo** [comment]
@mahamshahid18 That sounds like a publications issue! Perhaps you need to adjust line 40 on server/study_groups/methods.js so that `updatedAt` is published to the "all study groups" view? (Don't quote me on the line number, but I do think that's the file to look into.)

**Comment by mahamshahid18** [comment]
Hmm. Ok thanks, I'll take a look

**Comment by mahamshahid18** [comment]
Hey @lpatmo I figured it out. Here's how the study group card looks now (if there is an `updatedAt` field present):

![last-activity-on-study-group-card](https://user-images.githubusercontent.com/12479952/46878188-1508a000-ce5c-11e8-9cdb-26ea8cad38ae.PNG)

Is this good or do you want any changes to it?

**Comment by lpatmo** [comment]
That looks great!

**Comment by mahamshahid18** [comment]
Ok then I'll submit a PR for this :)

**Comment by ronnykaizer** [comment]
this is a great idea but i also suggest that your studygroup should also support a skype for members who a apart from each

**Comment by lpatmo** [comment]
@ronnykaizer Can you say more? Study groups do support remote hangouts. All of the meetings/groups on CodeBuddies are remote and we don't have any that are in-person because part of the mission is not to be geographically exclusive.
