### ISSUE TITLE
Learning tweets should contain user twitter handle mention, if available

### ISSUE THREAD

**Issue by brylie** [codebuddies/codebuddies#967]
In PR #333, users were allowed to share learnings via a tweet. The learning tweet contains their codebuddy username, like so:

> [learning] ~ [username] #todayiLearned.

As an enhancement to this, it would be cool if the user's Twitter handle were @ mentioned, if one is available.

> [learning] ~ @[twitter_handle] #todayiLearned

**Comment by lpatmo** [comment]
++

In a user's CB profile, users _are_ given the option to fill out a twitter handle, so perhaps we could:
- check that a user has saved a twitter handle
- if so, append `@twitter_handle` to the learning they're sharing, assuming they've checked the checkbox to give the CB app permission to share on twitter.

![image](https://user-images.githubusercontent.com/4512699/46131066-9f5fcb80-c1ef-11e8-8c15-3447587508af.png)

**Comment by vinmaster** [comment]
I would like to tackle this issue

**Comment by railsstudent** [comment]
@vinmaster It is yours.  Have fun!!!

**Comment by lpatmo** [comment]
@vinmaster Let us know if you have questions!
