### ISSUE TITLE
Allow users to change first and last name

### ISSUE THREAD

**Issue by brylie** [codebuddies/codebuddies#968]
Feature request

What is the current behavior?
Users cannot change first and last name.

What is the expected behavior?
Users should be able to change first and last name

**Comment by stain88** [comment]
Curious, what's the use case for having first/last name on the site, and editable?

**Comment by brylie** [comment]
That's a good question, and brings up a broader decision. 

The site asks for first and last name during sign up. If we don't want to use them at all, then it might be good to remove them from the profile. Since we already have them as part of the profile, we should allow the end-user to change their info, along with other profile fields.

**Comment by stain88** [comment]
Oh really? @lpatmo @distalx has that always been the case? I really don't remember having to do that, but that doesn't mean I didn't do it!

**Comment by brylie** [comment]
My colleague registered on the site yesterday, via GitHub, and was asked for a first and last name.

**Comment by stain88** [comment]
I'm not denying it's the case now, maybe it's something that was added in when GitHub sign-in was added. Maybe @railsstudent has info too?

**Comment by brylie** [comment]
Jeppers, just clarifying the context (i.e. steps to reproduce).

**Comment by distalx** [comment]
@brylie 
Thanks a lot for filing this issue! 
@stain88 
The sign-in workflow has been changed, since we have enabled sign-in with github. 
Earlier (when we only had slack sign-in option) we used to get `firstname` and `lastname` from slack-api, but thats not the case with github. So I guess we added that step.
