### ISSUE TITLE
Add three new fields to the signup screen

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#970]
When a new user logs in via Slack or Github for the first time, they are asked to fill out their name. Let's add three new fields to this screen, and also make these three fields editable on the profile page (see: profile-edit.html and profile-edit.js). 

The three fields:
- One-line intro of yourself
- What skill(s) can you help others with?
- What skill(s) do you want to improve on?

See screenshot for details on how the UI should look.
![image](https://user-images.githubusercontent.com/4512699/46132596-442fd800-c1f3-11e8-8b58-a77783b094ec.png)

To contributors:
1) Please check out https://docs.codebuddies.org to get your environment set up! 
2) Reply to this thread to claim this issue.
3) If you have any questions, please ask in thread. :) 

This is mostly an HTML/CSS issue, with a tiny bit of javascript/meteor. Let me know if you need help.

**Comment by AjayPoshak** [comment]
I would like to take it.

**Comment by railsstudent** [comment]
@AjayPoshak  It is yours.

**Comment by hiteshpr** [comment]
Is the issue over? I am interested.

**Comment by stain88** [comment]
There's currently a PR under review, @hiteshpr

**Comment by hiteshpr** [comment]
No problem @stain88. Let me know if any new issue opens up.
