### ISSUE TITLE
Hide the "24 people in 24/7 hangout" message on codebuddies.org/coworking

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#971]
Until we can figure out why the wrong count is showing up underneath the Jitsi hangout frame, an easy "fix" would be to hide that particular message using CSS on https://codebuddies.org/silent. 

NOTE: Please only hide the message for the codebuddies.org/silent, not for any other pages. This means a CSS fix is required.

Getting started:
1) Check out https://docs.codebuddies.org
2) Reply to this thread to claim this issue, and let us know if you have questions! :)

**Comment by AjayPoshak** [comment]
I would like to take it.

**Comment by railsstudent** [comment]
@AjayPoshak  It is yours.

**Comment by kdaker** [comment]
@AjayPoshak are you still working on this?
