### ISSUE TITLE
Slack API: Send auto-email invite to user to codebuddies.slack.com when new user registers for the first time

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#972]
Instead of asking users to sign up for the Slack and for the website separately, we should send an auto-invite to the user's email to codebuddies.slack.com as soon as they log in for the first time on codebuddies.org. 

Note:
- if a user chooses to log in via another Slack account, we'll still have their email when they sign up, and we should send an invite to that email.
- if a user chooses to log in via Github, we'll have that email instead for invite-sending.

**Comment by lpatmo** [comment]
Note: If this feature is completed, it'll mean that we can remove https://codebuddiesmeet.herokuapp.com links from the home page, and have it around as a backup for logged-in users in case the auto-invite email fails.

**Comment by railsstudent** [comment]
I will work on it after finishing #948

**Comment by rahul1995** [comment]
I am looking into this for time being?

**Comment by rahul1995** [comment]
Can I look into this for time being?

**Comment by railsstudent** [comment]
@rahul1995  I am working on it now.

**Comment by railsstudent** [comment]
@lpatmo I would like to clarify the scope of this task.
![screen shot 2018-10-04 at 3 36 00 am](https://user-images.githubusercontent.com/1159649/46459369-b752c480-c786-11e8-890c-4b23039f421c.png)
Does the auto-invite email look similar to the one sent by Slack? I have question about the underlying url of the Join Now button.  It is created by Slack, I would not able to generate it.  Please advise. thanks.

**Comment by lpatmo** [comment]
I think we need to use the undocumented `user.admin.invite` method from Slack: https://github.com/ErikKalkoken/slackApiDoc/blob/master/users.admin.invite.md

I found a short tutorial at https://www.robinwieruch.de/slack-invite-javascript-react/ which uses React, but covers the basics. Eg:

```
import axios from 'axios';

var SLACK_TOKEN = 'my-slack-token-xxx';
var SLACK_INVITE_ENDPOINT = 'https://slack.com/api/users.admin.invite';

function inviteSuccess() {
  console.log('success');
}

function inviteError() {
  console.log('error');
}

function inviteToSlack(email) {
  var QUERY_PARAMS = `email=${email}&token=${SLACK_TOKEN}&set_active=true`;

  axios.get(`${SLACK_INVITE_ENDPOINT}?${QUERY_PARAMS}`)
    .then(inviteSuccess)
    .catch(inviteError);
}```

I'm not sure if you're able to create a legacy API token on your own, but if you need one, let me know.

**Comment by lpatmo** [comment]
If a user signs using in Slack using a different Slack (because they are not a member of the CB Slack yet), we'll still grab their email address associated with that Slack account, and they'll see the welcome screen where they'll fill out the rest of their info like first name, last name, username, intro, and skills. 

Then, theoretically/ideally, the automatic invite-to-CB-Slack will fire, and they'll then have an account with CB Slack.

The next time they sign in using Slack, and if they choose CB Slack, they'll get connected to the same account the originally signed up with because the email address matches.

**Comment by railsstudent** [comment]
@lpatmo  I saw the welcome screen and input the entry as expected.
In my test slack gmail account, I saw this instead.

![connected-app](https://user-images.githubusercontent.com/1159649/46554441-3e4e8c80-c8ae-11e8-91b5-a646f6bd075d.png)

**Comment by lpatmo** [comment]
That looks fine, since we haven't built the invite-a-user-to-Slack feature yet. I think even if the user disconnects this test Slack account from the "Connected Accounts" page, the next time they log in to cb.org using a Slack account with this email, we'll still recognize them.

**Comment by railsstudent** [comment]
Then, they will not receive email with the Join Now button to join codebuddies workspace.

**Comment by railsstudent** [comment]
I don't know if it is bad wifi at airport or bad code, I do not receive email when logging with github account. I will leave it until I return to HK.
