### ISSUE TITLE
Let users edit their profile re: skills they can help others with, and skills they want to improve on

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#985]
I just merged in PR#974 (https://github.com/codebuddies/codebuddies/pull/974/files) to the `staging` branch, which adds three new fields to the Users collection: `intro`, `skillsHelpOthersWith`, and `skillsWantToImprove`. 

![image](https://user-images.githubusercontent.com/4512699/46336547-fdb9ef00-c5df-11e8-8789-5bba91d3a9a2.png)

### 1) Give users the ability to go to their profile page and edit/update these three fields when they click on "edit". Not sure what the design should look like; perhaps the two new textareas on skills could be stacked below the "bio" textarea? 

![image](https://user-images.githubusercontent.com/4512699/46336743-889ae980-c5e0-11e8-8c8b-ac47fb69c444.png)

### 2) On the profile page currently, there is a textarea for `bio`. We shouldn't have both `bio` and `intro`. Let's keep `bio` (since existing users will have already saved data to that field) and rename the `intro` field on the new user signup page to be `bio`. 

![image](https://user-images.githubusercontent.com/4512699/46336767-98b2c900-c5e0-11e8-93c3-934fdfbdb790.png)

Please comment if you'd like to work on this issue. If you have trouble figuring out which files to look at, please give a shout!

Tips for new contributors:
1) To get set up, take a look at our docs at https://docs.codebuddies.org
2) Once you have localhost:3000 running, hit control-m on your keyboard to take a look at the data rendered on each page of the app. You can change around the data, too!

**Comment by tarunjindal790** [comment]
I am working on this. :)

**Comment by lpatmo** [comment]
@tarunjindal790 Thanks! I will mark this as claimed for you. :) Let us know if you need help.

**Comment by tarunjindal790** [comment]
Hey, @lpatmo Sorry for the delay but I am stuck whenever I try to run the project .The terminal shows up downloading meteor-tool and freeze there.I have been trying to fix it for hours but nothing seems to work.

**Comment by lpatmo** [comment]
@tarunjindal790 Sorry, I missed your message somehow! I will mark this as `unclaimed`. What OS are you on? What was the error, and did the error happen when you were running the meteor install command?

**Comment by NicBonetto** [comment]
@lpatmo I can take this on if it is still unclaimed.

**Comment by railsstudent** [comment]
@NicBonetto It is still unclaimed. You are welcome to work on it. Thanks.

**Comment by NicBonetto** [comment]
@railsstudent Ok sounds good. Just for clarification, I am merging this to the `staging` branch not `master` branch correct?

**Comment by stain88** [comment]
yeah, branch from `staging`, back to `staging`

**Comment by nathanejbrown** [comment]
I can probably knock this out. My thinking is that I would send the skills to the back end as an array. Is there another data structure that's preferable?

**Comment by lpatmo** [comment]
@nathanejbrown Sorry, @NicBonetto just submitted a PR for this issue. Re: your question, for future reference -- the `skills` is a textarea, so would be submitted to the backend as a string.
