### ISSUE TITLE
[Bug] Github signup takes two tries

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#986]
On codebuddies.org, users can sign up one of two ways:
- sign up using Github (automatic auth)
- sign up via a Slack account (ideally their CodeBuddies Slack account)

I've noticed new users sometimes taking two tries of clicking on the "Sign in with Github" button before the app truly registers their username and logs them in via Github.

I can sometimes replicate this, and sometimes not. This will probably be a tough issue to track down, but wanted to file in case there was a solution. 

![image](https://user-images.githubusercontent.com/4512699/46337134-b46a9f00-c5e1-11e8-8c52-ca8cd4124f07.png)

**Comment by 20djm** [comment]
I can try working on this one

**Comment by 20djm** [comment]
@lpatmo I've really tried to replicate this bug, but I haven't been able to. I also reviewed the existing functionality for the sign in with github button, and I haven't found any glaring errors. Of course, this doesn't mean that there isn't a bug in there somewhere; however, if there is, I don't think I can find it anytime soon.

**Comment by lpatmo** [comment]
@20djm Thank you for taking a look! I will leave this issue up in case anyone else is able to replicate it.

**Comment by rahul1995** [comment]
Can I try looking into this one?
