### ISSUE TITLE
Minor CSS issue: black-text-on-red-button

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#987]
Entirely minor issue. If I am a moderator for the site, and I go to the hangout page for a hangout another user scheduled, I'll see some moderator-only features like a "Delete" button.

Currently, it's black text on red button. And the "M" icon indicating "Moderator" is too close to it. 

Fix:
- either remove red background `warning` CSS class or update that color of that button text to white
- add a space next to one of those "M" icons

![image](https://user-images.githubusercontent.com/4512699/46338270-89357f00-c5e4-11e8-95c1-4dd03a9682d3.png)

Note: 
Recreating this screen will take a few steps. You'll need to:
1) Sign in as a new user via Github on localhost:3000. Make this user a moderator. 
2) Sign in as another user via Slack on localhost:3000. Create a hangout.
3) Log out and sign back in as the first user. Notice a hangout page looking like the screenshot above.

If anyone (@distalx, @Connie) has ideas for how to make these replication steps easier, please chime in!

**Comment by tarunjindal790** [comment]
I am trying to work on this.

**Comment by lpatmo** [comment]
@tarunjindal790 Thanks! I just realized I didn't give clear instructions on *how* to make yourself a moderator once you've logged into localhost:3000; here are the instructions:

https://github.com/codebuddies/codebuddies/blob/staging/contributing.md#how-do-i-start-up-the-app-locally-and-log-in-as-an-admin

**Comment by tarunjindal790** [comment]
Thanks for this! I was a bit confused there. @lpatmo

**Comment by lpatmo** [comment]
Np! If you get stuck somewhere or if it doesn't work let me know!

**Comment by tarunjindal790** [comment]
Hey, @lpatmo Sorry for the delay but I am stuck whenever I try to run the project .The terminal shows up downloading meteor-tool and freeze there.I will try to make things right.Meanwhile,I think @9jaswag can take up the issue.

**Comment by 9jaswag** [comment]
Okay. I'll work on it

**Comment by 9jaswag** [comment]
@lpatmo I have been able to set up the app locally and I'm trying to add myself as an admin but the instruction just says `add your email and username to settings-development.json.` without saying how. Is there a particular key/value pair for adding email and username?

**Comment by lpatmo** [comment]
@tarunjindal790 Sorry that happened! You were stuck on the installing meteor step? Could you file a new Github issue with some details about which OS you are using and the error message you got?  I can help you troubleshoot there.

@9jaswag The two lines to changes are 41 and 42 in settings-development.json, here: 
```
  "root_email":"codebuddiesdotorg@gmail.com",
  "root_username":"CB",
```

Hope this helps! And for some reason if the email is not firing, let me know and I will DM you an updated Sparkpost API key, which might be necessary.

**Comment by 9jaswag** [comment]
@lpatmo I'll give that a try. Thanks

**Comment by 9jaswag** [comment]
@lpatmo I got an `Error: Invalid login` error when resetting Meteor and running the app after adding my email and username

**Comment by lpatmo** [comment]
@9jaswag Sorry I missed this. Can you share a screenshot of the `Error: Invalid login` message you're seeing? I'm a little confused about the error message.

**Comment by shuayb01** [comment]
Is this still open?

**Comment by lpatmo** [comment]
@shuayb01 I believe @9jaswag is working on this, sorry! We just managed to get the admin password firing. I will update contributing.md and docs.codebuddies.org with some updated instructions about the gotchas involved.

**Comment by 9jaswag** [comment]
I'll be raising a pull request for the issue today
