### ISSUE TITLE
Remove "I'm working on..." section from /hangouts; default to list of learnings

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#988]
Sadly, because the https://github.com/mizzao/meteor-user-status package was deprecated, our box displaying the count of current users online and each users' current status is not working anymore. 

The original idea was that folks would have codebuddies.org/hangouts open, see other users and their current status message as they logged in, mark whether they were up for a silent/teaching/collaborative and be able to create hangouts spontaneously based on other people's statuses. 

I'm not sure if this feature was ever used to its full potential. But in any case, because we can't track online users anymore, here is my proposal:

1) Remove the "I'm working on..." tab:
![image](https://user-images.githubusercontent.com/4512699/46341064-1e884180-c5ec-11e8-9133-174707903d52.png)

2) Only feature one tab on this sidebar: the "Today I learned..." tab.

3) At the moment, the # of global recent learnings appearing on this sidebar is 5. Let's increase it to 10. 

![image](https://user-images.githubusercontent.com/4512699/46341185-64dda080-c5ec-11e8-8391-638907ceaa08.png)

====
### Notes for new contributors:
1) Please check out https://docs.codebuddies.org to get started!
2) Leave a comment if you'd like to work on this issue.
3) Let us know if you have questions. 

This is mostly an HTML/CSS issue, but may require navigating around Meteor/Spacebars syntax (very similar to Handlebars or other templating language!). If you get stuck, please ask.

**Comment by LeomarAmiel** [comment]
Working on it! 😁
