### ISSUE TITLE
Slack API: share a learning to CodeBuddies directly from Slack (@cb_jarvis)

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#990]
Currently, users can schedule a hangout directly from Slack (see: https://github.com/codebuddies/codebuddies/pull/943). 

On the site, we have a learnings tracker that hasn't gotten a lot of love (only ~300 learnings reported):

![screen shot 2018-10-02 at 2 55 54 am](https://user-images.githubusercontent.com/4512699/46342070-b6872a80-c5ee-11e8-9835-64180a1f866e.jpg)

As you might be able to tell from the screenshot, these learnings are typically shared on codebuddies.org/hangouts, underneath a hangout iframe on a hangout page, or in a study group tab. 

## TODO: 
1) Let users share a learning directly from Slack by typing in `@cb_jarvis #todayilearned [message]`

2) This message will appear as a learning under the `Learnings` collection, and be tied back to the user who submitted it.

![screen shot 2018-10-02 at 2 59 20 am](https://user-images.githubusercontent.com/4512699/46342277-31e8dc00-c5ef-11e8-9f6d-a94d5f6e2b22.jpg)

3) Take a look at https://github.com/codebuddies/codebuddies/pull/943 for guidance on how to align a CodeBuddies Slack user email with the same user email on codebuddies.org.

**Comment by Bigocb** [comment]
I would like to try this one!

**Comment by railsstudent** [comment]
@Bigocb it's your to tackle

**Comment by railsstudent** [comment]
Let me try to do it.

**Comment by railsstudent** [comment]
@lpatmo Welcome, anything for Codebuddies.  Let me study at #943 to see how the incredible @gauravchl  did. I hope not to disturb him unless I am really stuck on the task.

**Comment by lpatmo** [comment]
Looks like the syntax `#til I learned something` won the poll. :) So, no need to reference @cb_jarvis. 

![image](https://user-images.githubusercontent.com/4512699/47949950-4ed34080-df08-11e8-97c5-d07a789349d8.png)

**Comment by railsstudent** [comment]
@lpatmo  @gauravchl  Can I use the cb_jarvis bot to process todayILearnt event and then call meteor server to create today I learnt record in mongodb?

If not, I will need to create a new bot. Will each slack callback process by cb_jarvis and my new bot.

Please correct me if I am wrong.  Should I add til logic to message-parser.js and webhook.js or make new message parser and webhook?

Please advise.

**Comment by gauravchl** [comment]
> Should I add til logic to message-parser.js and webhook.js 

Yup +1

**Comment by lpatmo** [comment]
My prediction is users will find it easier to type #2 (#til message) but I
don't mind #1 (@cb_jarvis til message) if it's much easier to implement. We
can try it out and see what people do!

**Comment by lpatmo** [comment]
Thank you both! Enjoy the conference, Connie!

**Comment by gauravchl** [comment]
Sweet! 

> If using the same cb_jarvis, what is the setup? 

The setup is:

1. Update the message-parser.js, add new command and reply inside `ActionTable` variable.
   ```
    const ActionsTable = [
      ...
      ...
    {
      command: "#til",
      reply: `Thank you! Your til message is being posted...`
    }
    ];
   ```
      reply is optional.

2. Update webhook.js:
```
// Update processEvent function
if (action.command === "#til") {
  return webhooks.postTodayILearn(slackUserId, action, channel);
}



// create a new function postTodayILearn 
postTodayILearn(slackUserId, action, channel) {
   // Add a same logic as it is inside createHangout that checks
   // whether the slack user is also registered to codebuddies site 
   // may be refactor that logic from createHangout and make it reusable 

   // Next write a logic to post the til message to codebuddie's db
   // You can call the existing meteor method "addLearning" from `learnings/methods.js`
   // But keep in mind that it uses `this.userId`. 
   // And this.userId will always be undefined when calling that method from here.
   // You will have to refactor that method and pass the user who is creating the hangout explicitly.
   // For example see below commit where i refactored createHangout logic for the same purpose.
   // https://github.com/codebuddies/codebuddies/pull/943/commits/26729b0ec82a1d5c3632f23b86215908a0aea05c 

}
```
Let me know if you need any help.

Cheers!

**Comment by railsstudent** [comment]
@gauravchl  Thanks. I will make a stab at this issue after my trip.

**Comment by gauravchl** [comment]
@railsstudent cbJarvisId is userid of the bot, you can hover/click on the bot name from slack web UI and it will show you the ID, ex:(BCKRMFPR6)

<img width="540" alt="screen shot 2018-12-06 at 8 25 11 pm" src="https://user-images.githubusercontent.com/3471415/49591743-4fdb1000-f995-11e8-9411-ff9465b08347.png">

> Can I use any slack account to create an app, generate slack oauth token and replace the dummy value with the actual value in the json file?

Yes you can, I do also have a slack channel created for testing the jarvis, You can also test it there if you want. Let me know what's your email, will invite you there.
