### ISSUE TITLE
On profile page, add a textarea so users can type in something they learned directly above their log of learnings

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#991]
If you go to your profile page on https://codebuddies.org, you'll see a log of learnings that you've shared.

![screen shot 2018-10-02 at 3 02 15 am](https://user-images.githubusercontent.com/4512699/46342517-c9e6c580-c5ef-11e8-9e3e-5820cc814c6e.jpg)

Currently, there is no way to share a learning directly on this page.

Borrowing from the "Today I learned..." section from https://codebuddies.org/hangouts, we should add a textarea here that'll let users share a learning directly.

![screen shot 2018-10-02 at 3 02 40 am](https://user-images.githubusercontent.com/4512699/46342558-e5ea6700-c5ef-11e8-92e9-8025d3340a46.jpg)

## Note to contributors
Note: At first glance, this should be a fairly easy issue. We already have a template called `hangoutLearned`, so I think we can just drop it into the profile page using Spacebar syntax, like so:

```
{{> hangoutLearned }}
```

If you're unfamiliar with this syntax, please read through https://meteorcapture.com/spacebars/. Spacebars is a templating language inspired by Handlebars.

**Comment by codemzy** [comment]
I will have a go at this 😅
