### ISSUE TITLE
Clojure Status Icon

### ISSUE THREAD

**Issue by tyberious-1** [codebuddies/codebuddies#994]
Before you open an issue, please check if a similar issue already exists or has been closed before. Also please remember that you can also get help in the [#codebuddies-meta channel on the CodeBuddies Slack](https://codebuddiesmeet.slack.com/messages/codebuddies-meta/). (If you are not a member, you can get your invite from [here](http://codebuddiesmeet.herokuapp.com/).

Do you want to request a feature or report a bug?  Feature

What is the current behavior? Not able to change status icon to Clojure icon.

What is the expected behavior? Change status icon to Clojure icon.

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)

**Comment by lpatmo** [comment]
@tyberious-1 Are you talking about the status icon on Slack, or on the website?

**Comment by tyberious-1** [comment]
![image](https://user-images.githubusercontent.com/5651834/46387912-3537a280-c697-11e8-96d5-5c9dc2fa4083.png)

**Comment by lpatmo** [comment]
@tyberious-1 Ah, that's Slack, not a Github issue. Questions like that can go to #codebuddies-meta. I added a :clojure: emoji for you in the Slack workspace -- I think you should be able to get it now!
