### ISSUE TITLE
CSS: Improve hangout cards design based on mockup

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#998]
@angelocordon designed this last year:

![image](https://user-images.githubusercontent.com/4512699/46568605-9613e480-c8fc-11e8-9a2a-4743a61ed31d.png)
Source: https://github.com/codebuddies/codebuddies/issues/696

Right now one of our hangout cards on codebuddies.org/hangouts looks like this:
![image](https://user-images.githubusercontent.com/4512699/46568648-14708680-c8fd-11e8-95f4-f088ba3ed520.png)

TODO:
Make the hangout card look more like the mockup (the first image). 

For new contributors:
- Please read docs.codebuddies.org to get set up
- Let us know if you have any questions! We've also got a #cb-code channel on the CodeBuddies Slack.

**Comment by adityatandon007** [comment]
@lpatmo I would like to try this !

**Comment by mahamshahid18** [comment]
@lpatmo Hi. I'd like to work on this if this is still open?

**Comment by lpatmo** [comment]
Hey @mahamshahid18, we still need help with this issue! PR#999 added some changes, so it now looks like this:
![image](https://user-images.githubusercontent.com/4512699/46577999-50acf100-c9a8-11e8-9fbc-b794d2036adf.png)

But we want the card to look like this:
![image](https://user-images.githubusercontent.com/4512699/46578000-573b6880-c9a8-11e8-8c44-bbd6f3228e8e.png)

Let me know if you need help. Thanks!

**Comment by askesis** [comment]
@lpatmo I'll try make this task, but I have some questions.

1. Where is the `join now` button on a new card ? 
2. What is the `i` sign on a card header?

**Comment by mahamshahid18** [comment]
@lpatmo yes for sure, I'll work on this 👍

**Comment by mahamshahid18** [comment]
Hey @lpatmo here's how the cards are looking right now in different states.

**State: Hangout Scheduled**
![card-scheduled](https://user-images.githubusercontent.com/12479952/46705194-e9ad6780-cc47-11e8-89fa-e4817cf75876.PNG)

**State: Hangout Scheduled : card hover**
![card-scheduled-hover](https://user-images.githubusercontent.com/12479952/46705232-0c3f8080-cc48-11e8-9ebc-ac64eec61f87.PNG)

**State: Hangout In Progress**
![card-in-progress](https://user-images.githubusercontent.com/12479952/46705243-16fa1580-cc48-11e8-8432-fd0db8f97047.PNG)

**State: Hangout In Progress : card hover**
![card-in-progress-hover](https://user-images.githubusercontent.com/12479952/46705260-26795e80-cc48-11e8-9239-574779577ed5.PNG)

Please tell me if this is good to go, or if any changes are needed?

**Comment by lpatmo** [comment]
@mahamshahid18 That looks great! Thank you! Maybe one more check: could you test what it looks like if the study group name has many words? Perhaps we could truncate it using CSS (eg https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/). 

![image](https://user-images.githubusercontent.com/4512699/46713836-6707b680-cc0d-11e8-89e2-8b9c676cf80f.png)

Otherwise, feel free to submit a PR! Thanks again.

PS I just noticed a few more design suggestions @angelocordon mocked up in https://github.com/codebuddies/codebuddies/issues/696 to clean up the dates, but I will file those as new issues after this PR is merged. :)

**Comment by mahamshahid18** [comment]
@lpatmo I did check for long study group names and it looked very messy. Thanks for the link, I've added string truncating as well now. Here's how it looks 

![card-study-group-name-truncating](https://user-images.githubusercontent.com/12479952/46741815-384a1880-ccbf-11e8-9d6c-43fce2382dcb.PNG)

I'll submit a PR now :)
